/* Background tables — dungeon_crawler_carl.
   Mechanics and concise labels only (no rulebook prose).

   Structure: { id, roll (die size), startingRank, options: [{ name, skillIds, desc }] }.
   Every background references SHARED Skill catalog ids — backgrounds never
   own skill definitions. Players pick ONE background per category, then TWO
   of its three skills; duplicates across categories cannot stack.
   Human tables roll 1d12; animal tables roll 1d6.
   `desc` is a short Ginger Dragon explanatory summary (one sentence) shown
   to players before and after choosing — never quoted rulebook flavor text.
*/

const b = (name, skillIds, desc = "") => ({ name, skillIds, desc });

export const HUMAN_BACKGROUND_CATEGORIES = [
  {
    id: "childhood",
    label: "Childhood",
    roll: 12,
    startingRank: 1,
    options: [
      b("Latchkey Kid", ["streetwise", "perception", "stealth"],
        "You learned early how to handle yourself without much adult supervision."),
      b("Crafty Kid", ["fabricate", "repair", "salvage"],
        "You spent your childhood building, fixing, and taking things apart to see how they worked."),
      b("Excitable Kid", ["escape_artist", "endurance", "running"],
        "You burned off endless energy running, climbing, and squeezing out of tight spots."),
      b("Gymnast", ["endurance", "jumping", "performance"],
        "Years of gymnastics training gave you discipline, spring, and a taste for performing."),
      b("Military Brat", ["deception", "streetwise", "tactics"],
        "Moving between military bases taught you to read people and think tactically."),
      b("MMO Kid", ["fabricate", "engineering", "tactics"],
        "You spent your childhood gaming and developed technical and tactical instincts."),
      b("Only Child", ["good_first_impression", "investigation", "negotiation"],
        "Raised without siblings, you learned to make strong first impressions and negotiate for what you want."),
      b("Outdoor Kid", ["animal_handling", "climbing", "swimming"],
        "You grew up climbing, swimming, and spending plenty of time outdoors."),
      b("Problem Child", ["intimidate", "deception", "pugilism"],
        "You got into trouble often and learned to intimidate, bluff, and fight your way out of it."),
      b("Scamp", ["hide_in_shadows", "jumping", "throwing"],
        "You spent your childhood hiding, jumping fences, and throwing things you shouldn't have."),
      b("Teacher's Pet", ["catcher", "perception", "good_first_impression"],
        "You paid close attention in class, caught whatever came your way, and charmed the adults."),
      b("Wild Child", ["stealth", "survival", "running"],
        "You grew up feral and self-reliant, moving unseen and outlasting whatever came your way."),
    ],
  },
  {
    id: "adolescence",
    label: "Adolescence",
    roll: 12,
    startingRank: 1,
    options: [
      b("Family Farm", ["animal_handling", "fabricate", "tracking"],
        "You grew up working a farm, handling animals and mending whatever broke."),
      b("Drama Nerd", ["fabricate", "deception", "performance"],
        "You threw yourself into theater, learning to build sets and work a crowd."),
      b("Drop-Out", ["chopper_pilot", "streetwise", "survival"],
        "You left school early and scraped by on street smarts and self-reliance."),
      b("Greek Life", ["negotiation", "intimidate", "taunt"],
        "You spent your teen years in fraternity or sorority life, learning to negotiate, pressure, and razz."),
      b("Influencer", ["negotiation", "persuasion", "performance"],
        "You grew an online following and got practiced at persuading and performing for an audience."),
      b("Jock", ["endurance", "jumping", "throwing"],
        "You poured your teen years into sports, building endurance, power, and a strong arm."),
      b("McJob", ["determine_value", "negotiation", "repair"],
        "You worked service jobs and picked up a feel for prices, people, and quick repairs."),
      b("Popular", ["good_first_impression", "perception", "persuasion"],
        "You ran with the in-crowd, mastering first impressions and easy charm."),
      b("Religious", ["catcher", "first_aid", "persuasion"],
        "You were raised in a faith community and learned to care for people and talk them down."),
      b("Student Government", ["deception", "persuasion", "investigation"],
        "You learned school politics — spinning stories, winning votes, and digging up useful information."),
      b("Nerd", ["investigation", "repair", "fabricate"],
        "You spent your adolescence studying, tinkering, and fixing whatever was broken."),
      b("Weirdo", ["streetwise", "intimidate", "fabricate"],
        "You never fit in, so you learned the streets, how to unsettle people, and how to build odd things."),
    ],
  },
  {
    id: "career",
    label: "Career",
    roll: 12,
    startingRank: 3,
    options: [
      b("Criminal", ["deception", "stealth", "streetwise"],
        "You made a living outside the law, moving unseen and talking your way out of trouble."),
      b("Service Industry", ["dagger", "endurance", "sleight_of_hand"],
        "You survived long shifts in food service, quick with a blade and steady on your feet."),
      b("Small Business Owner", ["determine_value", "negotiation", "perception"],
        "You ran your own shop and developed an eye for value, deals, and details."),
      b("Medical", ["sleight_of_hand", "detect_lies", "first_aid"],
        "You worked in healthcare and learned practical medical and observational skills."),
      b("Law Enforcement", ["detect_lies", "handgun", "investigation"],
        "You carried a badge and learned to read people, handle a sidearm, and work a case."),
      b("Gig Worker", ["driving", "escape_artist", "negotiation"],
        "You pieced together a living gig by gig, driving hard and talking down every fare."),
      b("Teacher", ["detect_lies", "perception", "performance"],
        "You spent years in classrooms, quick to spot a lie and practiced at holding attention."),
      b("Office Drone", ["dumpster_diving", "endurance", "investigation"],
        "You endured cubicle life, digging through records and grinding through long days."),
      b("Entertainer", ["deception", "good_first_impression", "performance"],
        "You performed for a living, all charm, showmanship, and stage-ready lies."),
      b("Unhoused", ["dumpster_diving", "streetwise", "survival"],
        "You survived without a home, learning where to find what others throw away."),
      b("Middle Manager", ["deception", "intimidate", "negotiation"],
        "You managed people from the middle, blending pressure, spin, and negotiation."),
      b("Military", ["handgun", "survival", "tactics"],
        "You served in the armed forces, trained with a sidearm in tactics and survival."),
    ],
  },
  {
    id: "hobby",
    label: "Hobby",
    roll: 12,
    startingRank: 2,
    options: [
      b("Collector", ["fabricate", "determine_value", "investigation"],
        "You collect things obsessively and know how to find, fix, and price them."),
      b("Cosplay", ["fabricate", "performance", "salvage"],
        "You build and perform in costume, crafting props out of salvaged junk."),
      b("Drinker", ["deception", "intimidate", "streetwise"],
        "You hold court at the bar, trading bluffs, banter, and intimidation."),
      b("Gamer", ["aiming", "perception", "tactics"],
        "You play shooters and strategy games, sharpening your aim and your tactical eye."),
      b("Gym Rat", ["running", "endurance", "swimming"],
        "You practically live at the gym, all cardio and laps in the pool."),
      b("Hunting", ["tracking", "shotgun", "stealth"],
        "You hunt for sport, patient with a rifle and quiet in the brush."),
      b("Music", ["perception", "performance", "sleight_of_hand"],
        "You play music, sharpening your ears, your stage presence, and your quick fingers."),
      b("Motorsports", ["driving", "repair", "salvage"],
        "You wrench and race in your spare time, fast behind the wheel and handy with tools."),
      b("Climber", ["climbing", "jumping", "endurance"],
        "You climb for fun, pulling hard, leaping gaps, and outlasting the wall."),
      b("Pop Culture", ["determine_value", "investigation", "perception"],
        "You are a walking trivia bank of shows, games, and collectibles, always spotting what matters."),
      b("Tinkering", ["engineering", "repair", "salvage"],
        "You spend your free time fixing, building, and cannibalizing anything mechanical."),
      b("Travel", ["endurance", "negotiation", "streetwise"],
        "You roam whenever you can, tough from the road and quick to haggle."),
    ],
  },
];

/* Animal crawlers use these tables INSTEAD of the Human tables. */
export const ANIMAL_BACKGROUND_CATEGORIES = [
  {
    id: "youth",
    label: "Youth",
    roll: 6,
    startingRank: 1,
    options: [
      b("Abandoned", ["hide_in_shadows", "endurance", "survival"],
        "You were left to fend for yourself, learning to hide and to survive alone."),
      b("Farmed", ["escape_artist", "climbing", "light_on_your_feet"],
        "You grew up on a farm, forever escaping pens and clambering over fences."),
      b("Litter-Raised", ["animal_handling", "detect_lies", "back_claw"],
        "You grew up in a boisterous litter, learning to read others and scrap for your share."),
      b("Pampered", ["negotiation", "good_first_impression", "persuasion"],
        "You were spoiled rotten and learned charm, flattery, and getting your way."),
      b("Runt", ["hide_in_shadows", "escape_artist", "stealth"],
        "You were the smallest of the litter and survived by hiding and slipping away."),
      b("Stray", ["back_claw", "streetwise", "survival"],
        "You lived on the streets, scrappy and street-smart, hunting for every meal."),
    ],
  },
  {
    id: "training",
    label: "Training",
    roll: 6,
    startingRank: 1,
    options: [
      b("Clever", ["investigation", "detect_lies", "dodge"],
        "You were taught to think, observing closely and dodging what you can't outsmart."),
      b("Free Range", ["escape_artist", "survival", "tracking"],
        "You roamed loose, escaping anything that tried to contain you and finding your way back."),
      b("Pack Mentality", ["animal_handling", "persuasion", "tactics"],
        "You learned to work with a pack, coordinating and persuading as a team."),
      b("Mischievous", ["deception", "persuasion", "sleight_of_hand"],
        "You were a little troublemaker, sweet-talking and stealing treats."),
      b("Watcher", ["ambush", "investigation", "perception"],
        "You spent your days watching everything closely, patient and observant."),
      b("Well-Trained", ["light_on_your_feet", "catcher", "performance"],
        "You were drilled thoroughly, graceful, obedient, and polished for show."),
    ],
  },
  {
    id: "quirk",
    label: "Quirk",
    roll: 6,
    startingRank: 2,
    options: [
      b("Chow Hound", ["dumpster_diving", "investigation", "intimidate"],
        "You will eat anything, and you know exactly where the good garbage is."),
      b("Cuddly", ["good_first_impression", "persuasion", "negotiation"],
        "You win everyone over with affection and never take no for an answer."),
      b("Curious", ["climbing", "perception", "swimming"],
        "You have to investigate everything, climbing, sniffing, and splashing right into it."),
      b("Hunter", ["hide_in_shadows", "stealth", "tracking"],
        "You never lost the instinct to stalk, hide, and track your prey."),
      b("Playful", ["persuasion", "dodge", "intimidate"],
        "You turn everything into a game, dodging and roughhousing with total confidence."),
      b("Social", ["animal_handling", "taunt", "perception"],
        "You love being around people and animals, chatty and alert to every mood."),
    ],
  },
  {
    id: "adult",
    label: "Adult",
    roll: 6,
    startingRank: 3,
    options: [
      b("Guard", ["catcher", "perception", "taunt"],
        "You spent your adulthood standing watch, catching what comes and keeping others in line."),
      b("Pile of Floof", ["escape_artist", "deception", "persuasion"],
        "You coast through life on fluff and charm, slipping loose of any grip."),
      b("Scrapper", ["light_on_your_feet", "streetwise", "survival"],
        "You fought for your place in the world, quick-footed and tough as nails."),
      b("Show Animal", ["good_first_impression", "light_on_your_feet", "performance"],
        "You were bred and trained for the ring, all polish, poise, and presence."),
      b("Support Animal", ["determine_value", "first_aid", "perception"],
        "You spent your life caring for others, steadying them and sensing their needs."),
      b("Working", ["animal_handling", "endurance", "perception"],
        "You worked for a living — herding, hauling, or guiding — and it shows in your endurance and focus."),
    ],
  },
];