import React from "react";
import { makeThresholdLookup } from "@/rules-profile";
import { rollDice } from "@/components/character/dice";
import Die from "@/components/character/DiceVisual";

/* Step 3 — CORE STATS (Step 3B.4). The five starting Core Stats are
   generated by ONE of the ACTIVE PROFILE's stat methods — Standard Array
   (assign each profile value exactly once) or Roll the Dice (1d6 per stat
   in profile order, reroll faces rerolled, no swapping). Everything is
   profile-driven: stat order, array values, die size, reroll faces, and
   the official Stat Mod threshold table — the SAME shared modifier lookup
   the Character Sheet uses, never a second formula. Enhanced =
   Unenhanced at starting creation; no enhancements are applied yet, and
   no derived stats (HP/Mana/Evade) are computed here. The wizard draft
   holds the choices; no Character record is created in this step. */

/* Player-facing labels for the profile's method ids. */
const METHOD_LABELS = {
  standard_array: "Standard Array",
  leave_it_to_chance: "Roll the Dice",
};

const Message = ({ children }) => (
  <span className="min-h-[1.25em] font-fell text-[13px] italic leading-snug text-[var(--hp)]">
    {children ?? ""}
  </span>
);

const CHOICE_BASE =
  "border border-[var(--ink-soft)] px-3 py-2.5 text-left transition-colors focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[var(--ink)]";
const CHOICE_OFF = "bg-[rgba(255,248,220,0.25)] hover:bg-[rgba(74,55,39,0.18)]";
const CHOICE_ON = "bg-[rgba(74,55,39,0.28)]";

export default function StepCoreStats({ draft, updateDraft, profile, errors = {} }) {
  const stepDef = profile?.creation_flow?.steps?.find((s) => s.id === "stats") ?? null;
  const methods = stepDef?.methods ?? [];
  const statsOrder = profile?.stats?.order ?? [];
  const defs = profile?.stats?.definitions ?? {};
  /* ONE modifier lookup — the profile's official threshold table, the same
     shared helper the Character Sheet uses. Derived from the ENHANCED stat. */
  const modLookup = React.useMemo(
    () => makeThresholdLookup(profile?.stats?.mod_rule?.table ?? []),
    [profile]
  );

  const cs = draft.coreStats ?? {};
  const methodDef = methods.find((m) => m.id === cs.method) ?? null;
  const arrayDef = methodDef && Array.isArray(methodDef.values) ? methodDef : null;
  const rollDef = methodDef?.roll ? methodDef : null;
  const allRolled =
    statsOrder.length > 0 && statsOrder.every((k) => typeof cs[k]?.enhanced === "number");

  /* Transient roll reveal — the draft already holds the TRUE stored results
     the instant the dice are thrown; the animation only settles each die
     onto its own stored value, in profile stat order (STR, INT, CON, DEX,
     CHA). Displayed finals always match the stored rolls. */
  const [anim, setAnim] = React.useState(null); // { revealed: 0..statsOrder.length }
  const timersRef = React.useRef([]);
  React.useEffect(() => () => timersRef.current.forEach(clearTimeout), []);

  const methodLabel = (m) => METHOD_LABELS[m.id] ?? m.id;
  const methodBlurb = (m) =>
    Array.isArray(m.values)
      ? `Assign ${m.values.join(", ")} once each.`
      : `Roll 1d${m.roll?.die ?? 6} for each stat in order. Reroll ${(m.roll?.reroll ?? []).join(", ")}s. No swapping.`;

  /* Switching methods clears the inactive method's values cleanly — the
     active method is authoritative and methods are never mixed. */
  const selectMethod = (m) => {
    if (cs.method === m.id) return;
    const cleared = { method: m.id };
    statsOrder.forEach((k) => {
      cleared[k] = null;
    });
    timersRef.current.forEach(clearTimeout);
    timersRef.current = [];
    setAnim(null);
    updateDraft({ coreStats: cleared });
  };

  const assign = (key, raw) => {
    const v = raw === "" ? null : parseInt(raw, 10);
    updateDraft({
      coreStats: { ...cs, [key]: v === null ? null : { enhanced: v, unenhanced: v } },
    });
  };

  /* A value taken by ANOTHER stat is disabled in this stat's dropdown;
     changing a stat releases its previous value back into the pool. */
  const takenByOther = (key, v) => statsOrder.some((k) => k !== key && cs[k]?.enhanced === v);

  /* Roll every stat from scratch, in profile order, rerolling the
     profile's reroll faces (1s) until a kept face appears. The kept face
     is stored permanently for that stat — no swapping, duplicates allowed. */
  const doRoll = () => {
    const dieSides = rollDef.roll?.die ?? 6;
    const reroll = rollDef.roll?.reroll ?? [];
    const results = statsOrder.map(() => {
      let r;
      do {
        r = rollDice(`1d${dieSides}`).total; // shared Ginger Dragon dice engine
      } while (reroll.includes(r));
      return r;
    });
    const next = { method: rollDef.id };
    statsOrder.forEach((k, i) => {
      next[k] = { enhanced: results[i], unenhanced: results[i] };
    });
    updateDraft({ coreStats: next });
    timersRef.current.forEach(clearTimeout);
    timersRef.current = [];
    setAnim({ revealed: 0 });
    statsOrder.forEach((_, i) => {
      timersRef.current.push(setTimeout(() => setAnim({ revealed: i + 1 }), 420 * (i + 1)));
    });
  };

  const modText = (key, settled) => {
    const v = cs[key]?.enhanced;
    return typeof v === "number" && settled ? `+${modLookup(v)}` : "";
  };

  return (
    <div className="flex flex-col gap-3">
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-2.5">
        {methods.map((m) => {
          const active = cs.method === m.id;
          return (
            <button
              key={m.id}
              type="button"
              onClick={() => selectMethod(m)}
              aria-pressed={active}
              className={`${CHOICE_BASE} ${active ? CHOICE_ON : CHOICE_OFF}`}
            >
              <span className="block font-fell-sc text-[16px] font-bold tracking-[0.04em] text-[#24180f]">
                {methodLabel(m)}
              </span>
              <span className="block font-fell italic text-[12px] text-[var(--ink-soft)]">
                {methodBlurb(m)}
              </span>
            </button>
          );
        })}
      </div>
      <Message>{errors.coreStatsMethod}</Message>

      {methodDef && (
        <>
          {rollDef && (
            <div className="flex flex-col items-center gap-2">
              <button
                type="button"
                onClick={doRoll}
                disabled={Boolean(anim)}
                className="ink-box px-4 py-2 font-fell-sc text-[15px] font-bold tracking-[0.06em] text-[#24180f]"
              >
                {allRolled ? "REROLL ALL" : "ROLL STATS"}
              </button>
              <Message>{errors.coreStatsValues}</Message>
            </div>
          )}

          <div className="flex flex-col gap-1.5 border-[1.5px] border-[var(--ink-soft)] bg-[rgba(255,248,220,0.2)] p-3">
            {statsOrder.map((key, i) => {
              const settled = !anim || i < anim.revealed;
              const value = cs[key]?.enhanced;
              return (
                <div key={key} className="flex items-center justify-between gap-3">
                  <span
                    className="w-10 font-fell-sc text-[14px] font-bold tracking-[0.06em] text-[#24180f]"
                    title={defs[key]?.label ?? key}
                  >
                    {key.toUpperCase()}
                  </span>
                  {arrayDef ? (
                    <select
                      value={value ?? ""}
                      onChange={(e) => assign(key, e.target.value)}
                      aria-label={`${defs[key]?.label ?? key} — ${methodLabel(methodDef)}`}
                      className="ink-box w-20 px-2 py-1 text-center text-[16px]"
                    >
                      <option value="">—</option>
                      {arrayDef.values.map((v) => (
                        <option key={v} value={v} disabled={takenByOther(key, v)}>
                          {v}
                        </option>
                      ))}
                    </select>
                  ) : (
                    <span className="flex h-9 w-20 items-center justify-center">
                      {typeof value === "number" ? (
                        <Die
                          sides={rollDef?.roll?.die ?? 6}
                          value={settled ? value : "?"}
                          rolling={!settled}
                          size={34}
                        />
                      ) : (
                        <span className="font-fell text-[16px] text-[var(--ink-faint)]">—</span>
                      )}
                    </span>
                  )}
                  <span className="w-10 text-right font-fell text-[15px] font-bold text-[#24180f]">
                    {modText(key, settled)}
                  </span>
                </div>
              );
            })}
            {arrayDef && <Message>{errors.coreStatsValues}</Message>}
          </div>
        </>
      )}
    </div>
  );
}