const STYLE='cc-beta-cleanup-style';
const PROFILE='cc-character-profile:';
function activeName(){return document.querySelector('#cc-character-dashboard-v2 .cc2-name')?.textContent?.trim()||document.querySelector('.character-bar select option:checked')?.textContent?.trim()||'Crawler'}
function key(){return PROFILE+encodeURIComponent(activeName())}
function load(){try{return JSON.parse(localStorage.getItem(key())||'{}')}catch{return {}}}
function save(v:any){localStorage.setItem(key(),JSON.stringify(v));window.dispatchEvent(new CustomEvent('cc:character-updated',{detail:{name:activeName()}}))}
function addStyle(){if(document.getElementById(STYLE))return;const s=document.createElement('style');s.id=STYLE;s.textContent=`
#cc-two-character-mode{overflow:auto!important;overscroll-behavior:contain!important;touch-action:pan-y!important}
#cc-two-character-mode .cc-two-grid{min-height:760px!important;overflow:visible!important}
#cc-two-character-mode iframe{min-height:740px!important}
@media(max-width:700px){#cc-two-character-mode .cc-two-grid{min-height:1180px!important;grid-template-rows:minmax(560px,1fr) minmax(560px,1fr)!important}#cc-two-character-mode iframe{min-height:560px!important}}
#cc-character-editor{padding:14px;margin-top:12px}#cc-character-editor .cc-edit-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}#cc-character-editor .cc-stat-grid{display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:6px}#cc-character-editor label{display:grid;gap:5px;font-size:13px}#cc-character-editor input,#cc-character-editor textarea{width:100%;box-sizing:border-box;background:#0c121a;color:#fff;border:1px solid var(--a,#b58a45);border-radius:8px;padding:9px}#cc-character-editor button{margin-top:10px;padding:9px 12px;border-radius:8px;border:1px solid var(--a,#b58a45);background:#171b22;color:#fff;font-weight:800}
#cc-runtime-gm-tools .cc-runtime-grid{order:1}#cc-runtime-gm-tools .cc-runtime-output{order:2}#cc-runtime-gm-tools .cc-runtime-output::before{content:'Generated Result';display:block;color:#e4b45e;font-weight:800;margin-bottom:8px}#cc-runtime-gm-tools{display:flex;flex-direction:column}#cc-runtime-gm-tools>h3:first-child,#cc-runtime-gm-tools>p:first-of-type{order:0}
@media(max-width:760px){#cc-character-editor .cc-edit-grid{grid-template-columns:1fr}#cc-character-editor .cc-stat-grid{grid-template-columns:repeat(3,1fr)}}`;document.head.appendChild(s)}
function applyProfile(){const root=document.getElementById('cc-character-dashboard-v2');if(!root)return;const p=load();if(p.name){const n=root.querySelector('.cc2-name');if(n)n.textContent=p.name}const meta=root.querySelector('.cc2-meta');if(meta&&(p.level||p.race||p.class))meta.textContent=`Level ${p.level||1} Crawler • ${p.race||'Human'} • ${p.class||'Crawler'}`}
function mountEditor(){const root=document.getElementById('cc-character-dashboard-v2');if(!root||document.getElementById('cc-character-editor'))return;const main=root.querySelector('.cc2-main');if(!main)return;const p=load();const sec=document.createElement('section');sec.id='cc-character-editor';sec.className='cc2-panel';sec.innerHTML=`<div class="cc2-title">✎ EDIT CHARACTER</div><div class="cc-edit-grid"><label>Name<input id="cc-edit-name" name="characterName" data-cc-field="name" value="${p.name||activeName()}"></label><label>Level<input id="cc-edit-level" name="level" data-cc-field="level" type="number" min="1" value="${p.level||1}"></label><label>Race<input id="cc-edit-race" name="race" data-cc-field="race" value="${p.race||'Human'}"></label><label>Class<input id="cc-edit-class" name="class" data-cc-field="class" value="${p.class||'Crawler'}"></label></div><div class="cc-stat-grid">${['STR','DEX','CON','INT','WIS','CHA'].map(k=>`<label>${k}<input id="cc-edit-${k.toLowerCase()}" name="${k.toLowerCase()}" data-cc-field="${k.toLowerCase()}" type="number" value="${p[k.toLowerCase()]??10}"></label>`).join('')}</div><label>Background / Notes<textarea id="cc-edit-notes" name="notes" data-cc-field="notes" rows="4">${p.notes||''}</textarea></label><button type="button" data-save-character>Save Character</button>`;main.appendChild(sec);(sec.querySelector('[data-save-character]') as HTMLButtonElement).onclick=()=>{const next:any={};sec.querySelectorAll<HTMLInputElement|HTMLTextAreaElement>('[data-cc-field]').forEach(i=>next[i.dataset.ccField!]=i.type==='number'?Number(i.value):i.value.trim());save(next);applyProfile()}}
function addEditButton(){const sub=document.querySelector('#cc-character-dashboard-v2 .cc2-subnav');if(!sub||sub.querySelector('[data-edit-character]'))return;const b=document.createElement('button');b.type='button';b.dataset.editCharacter='1';b.textContent='✎ Edit Character';b.onclick=()=>{mountEditor();document.getElementById('cc-character-editor')?.scrollIntoView({block:'center'})};sub.prepend(b)}
function tagCloud(){document.querySelectorAll<HTMLElement>('button,a').forEach(el=>{const t=(el.textContent||'').trim();if(/create cloud account|sign up|cloud account/i.test(t)&&!el.dataset.ccCloudBeta){el.dataset.ccCloudBeta='1';el.setAttribute('aria-disabled','true');el.title='Cloud accounts are not enabled in this beta build';el.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();alert('Cloud account creation is not enabled in this beta build yet. Local character data still works.')},true)}})}
let focusScroll=0;document.addEventListener('focusin',e=>{if((e.target as Element)?.matches('input,select,textarea'))focusScroll=window.scrollY},true);document.addEventListener('focusout',e=>{if(!(e.target as Element)?.matches('input,select,textarea'))return;const y=focusScroll;requestAnimationFrame(()=>{if(Math.abs(window.scrollY-y)>100)window.scrollTo({top:y,behavior:'auto'})})},true)
function apply(){addStyle();addEditButton();applyProfile();tagCloud()}
document.addEventListener('click',e=>{if((e.target as Element)?.closest('[aria-label="Primary navigation"],.character-bar,.cc2-subnav'))setTimeout(apply,80)},true);window.addEventListener('cc:character-updated',()=>setTimeout(apply,60));if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(apply,700),{once:true});else setTimeout(apply,700);
export {apply as applyBetaCleanup};