const STYLE='cc-character-interaction-cleanup-style';
const NOTES='cc-character-notes:';
function activeName(){return document.querySelector('#cc-character-dashboard-v2 .cc2-name')?.textContent?.trim()||document.querySelector('.character-bar select option:checked')?.textContent?.trim()||'Crawler'}
function primary(label:string){const nav=document.querySelector('[aria-label="Primary navigation"]');const b=[...(nav?.querySelectorAll<HTMLButtonElement>('button')||[])].find(x=>(x.textContent||'').replace(/✦/g,'').trim().toLowerCase()===label.toLowerCase());b?.click();return Boolean(b)}
function toast(msg:string){let t=document.getElementById('cc-ui-toast');if(!t){t=document.createElement('div');t.id='cc-ui-toast';document.body.appendChild(t)}t.textContent=msg;t.className='show';setTimeout(()=>t.className='',1400)}
function styles(){if(document.getElementById(STYLE))return;const s=document.createElement('style');s.id=STYLE;s.textContent=`#cc-character-dashboard-v2 .cc2-recent .cc-clear-rolls{float:right;border:1px solid var(--a);background:#111925;color:#fff;border-radius:7px;padding:5px 8px;font-size:11px}#cc-character-dashboard-v2 .cc2-subnav button{cursor:pointer}#cc-character-dashboard-v2 .cc2-quickgrid button{cursor:pointer}#cc-character-sheet-spells{display:block!important}#cc-character-sheet-spells button[data-cast]{display:inline-block!important;visibility:visible!important;opacity:1!important}#cc-ui-toast{position:fixed;left:50%;bottom:24px;transform:translate(-50%,18px);opacity:0;pointer-events:none;z-index:99999;background:#101722;border:1px solid #d69c42;color:#fff2ca;padding:10px 14px;border-radius:9px;transition:.18s}#cc-ui-toast.show{opacity:1;transform:translate(-50%,0)}.cc-inline-notes{padding:13px}.cc-inline-notes textarea{width:100%;min-height:150px;background:#0c131d;border:1px solid #475363;color:#fff;border-radius:8px;padding:10px;resize:vertical}`;document.head.appendChild(s)}
function scrollToEl(sel:string){const el=document.querySelector(sel) as HTMLElement|null;if(el){el.scrollIntoView({behavior:'smooth',block:'start'});return true}return false}
function notes(){const root=document.getElementById('cc-character-dashboard-v2');const main=root?.querySelector('.cc2-main');if(!main)return;let p=document.getElementById('cc-inline-notes') as HTMLElement|null;if(!p){p=document.createElement('section');p.id='cc-inline-notes';p.className='cc2-panel cc-inline-notes';p.innerHTML='<div class="cc2-title">📝 NOTES</div><textarea aria-label="Character notes" placeholder="Character notes..."></textarea>';main.appendChild(p);const ta=p.querySelector('textarea')!;ta.value=localStorage.getItem(NOTES+encodeURIComponent(activeName()))||'';ta.addEventListener('input',()=>localStorage.setItem(NOTES+encodeURIComponent(activeName()),ta.value))}p.scrollIntoView({behavior:'smooth',block:'start'});(p.querySelector('textarea') as HTMLTextAreaElement)?.focus()}
function wireRecent(){const p=document.querySelector('#cc-character-dashboard-v2 .cc2-recent') as HTMLElement|null;if(!p||p.querySelector('.cc-clear-rolls'))return;const title=p.querySelector('.cc2-title') as HTMLElement|null;if(!title)return;const b=document.createElement('button');b.type='button';b.className='cc-clear-rolls';b.textContent='Clear';b.onclick=()=>{const list=p.querySelector('ol,[data-cc2-recent]');if(list)list.innerHTML='';window.dispatchEvent(new CustomEvent('cc:recent-rolls-cleared',{detail:{character:activeName()}}));toast('Recent rolls cleared')};title.appendChild(b)}
function handleSubnav(btn:HTMLButtonElement){const t=(btn.textContent||'').replace(/^[^A-Za-z]+/,'').trim().toLowerCase();if(t.includes('character sheet'))scrollToEl('#cc-character-dashboard-v2 .cc2-hero');else if(t.includes('abilities'))scrollToEl('#cc-character-dashboard-v2 .cc2-skills');else if(t.includes('inventory'))primary('Inventory');else if(t.includes('journal'))primary('Progression');else if(t.includes('conditions'))scrollToEl('#cc-character-dashboard-v2 .cc2-cond');else if(t.includes('notes'))notes();else if(t.includes('theme')||t.includes('portrait')){scrollToEl('#cc-character-dashboard-v2 .cc2-portrait-wrap');(document.querySelector('#cc-character-dashboard-v2 [data-cc2-theme]') as HTMLSelectElement|null)?.focus()}}
function handleQuick(btn:HTMLButtonElement){const t=(btn.textContent||'').trim().toLowerCase();if(t.includes('inventory'))primary('Inventory');else if(t.includes('level'))primary('Progression');else if(t.includes('spell')){primary('Character');setTimeout(()=>scrollToEl('#cc-character-sheet-spells'),120)}else if(t.includes('rest')){window.dispatchEvent(new CustomEvent('cc:rest-request',{detail:{character:activeName()}}));const target=document.querySelector('#cc-character-sheet-spells') as HTMLElement|null;if(target)target.scrollIntoView({behavior:'smooth',block:'center'});toast('Rest action opened')}}
function brandText(){document.querySelectorAll<HTMLElement>('footer,*').forEach(el=>{if(el.children.length===0&&/Ginger Dragon Fire Studios/i.test(el.textContent||''))el.textContent=(el.textContent||'').replace(/Ginger Dragon Fire Studios/gi,'Ginger Dragon Studios')})}
function apply(){styles();wireRecent();brandText()}
document.addEventListener('click',e=>{const target=e.target as Element|null;const sub=target?.closest('#cc-character-dashboard-v2 .cc2-subnav button') as HTMLButtonElement|null;if(sub){e.preventDefault();handleSubnav(sub);setTimeout(apply,100);return}const q=target?.closest('#cc-character-dashboard-v2 .cc2-quickgrid button') as HTMLButtonElement|null;if(q){e.preventDefault();handleQuick(q);setTimeout(apply,100);return}if(target?.closest('[aria-label="Primary navigation"],.character-bar'))setTimeout(apply,120)},true);window.addEventListener('cc:character-updated',()=>setTimeout(apply,100));window.addEventListener('cc:campaign-changed',()=>setTimeout(apply,100));if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(apply,900),{once:true});else setTimeout(apply,900);export {apply as applyCharacterInteractionCleanup};