import { upgradeCharacterDice } from './character-dice-upgrade';
const ID='cc-character-wizard';
const BTN='cc-character-wizard-tab';
const PROFILE='cc-character-profile:';
function activeName(){return document.querySelector('#cc-character-dashboard-v2 .cc2-name')?.textContent?.trim()||document.querySelector('.character-bar select option:checked')?.textContent?.trim()||'Crawler'}
function key(){return PROFILE+encodeURIComponent(activeName())}
function load(){try{return JSON.parse(localStorage.getItem(key())||'{}')}catch{return {}}}
function ensurePanel(){let p=document.getElementById(ID) as HTMLElement|null;if(p)return p;p=document.createElement('section');p.id=ID;p.style.cssText='display:none;margin:14px 18px 24px;padding:18px;border:1px solid #b98538;border-radius:14px;background:#0b1118;color:#f6ead0';document.querySelector('[aria-label="Primary navigation"]')?.insertAdjacentElement('afterend',p);return p}
function render(){const p=ensurePanel(),d=load(),floor=Math.max(1,Number(d.floor||1)),locked=floor<3;p.innerHTML=`<h2 style="margin:0 0 6px;color:#e8b45b">🧙 Character Wizard</h2><p>Build and edit your crawler here. Race and Class unlock on Floor 3.</p><div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(170px,1fr));gap:10px"><label>Name<input name="characterName" data-f="name" value="${d.name||activeName()}"></label><label>Floor<input name="floor" data-f="floor" type="number" min="1" value="${floor}"></label><label>Level<input name="level" data-f="level" type="number" min="1" value="${Number(d.level||1)}"></label><label>Race<input name="race" data-f="race" value="${d.race||''}" ${locked?'disabled':''}></label><label>Class<input name="class" data-f="class" value="${d.class||''}" ${locked?'disabled':''}></label></div>${locked?'<p>🔒 Race and Class are locked until Floor 3.</p>':''}<div style="display:grid;grid-template-columns:repeat(6,minmax(60px,1fr));gap:6px;margin:12px 0">${['str','dex','con','int','wis','cha'].map(k=>`<label>${k.toUpperCase()}<input name="${k}" data-f="${k}" type="number" value="${Number(d[k]??10)}"></label>`).join('')}</div><label>Notes<textarea name="notes" data-f="notes" rows="5" style="width:100%">${d.notes||''}</textarea></label><div style="display:flex;gap:8px;flex-wrap:wrap;margin-top:12px"><button type="button" data-save>Save Character</button><button type="button" data-backup>Export Backup</button></div>`;p.querySelectorAll<HTMLInputElement|HTMLTextAreaElement>('input,textarea').forEach(x=>x.style.cssText='box-sizing:border-box;width:100%;background:#111923;color:#fff;border:1px solid #6f542f;border-radius:8px;padding:9px');(p.querySelector('[data-save]') as HTMLButtonElement).onclick=()=>{const next:any=load();p.querySelectorAll<HTMLInputElement|HTMLTextAreaElement>('[data-f]').forEach(i=>{if(i.disabled)return;next[i.dataset.f!]=i.type==='number'?Number(i.value):i.value.trim()});localStorage.setItem(key(),JSON.stringify(next));window.dispatchEvent(new CustomEvent('cc:character-updated',{detail:{name:next.name||activeName()}}));render()};(p.querySelector('[data-backup]') as HTMLButtonElement).onclick=()=>{const backup:any={exportedAt:new Date().toISOString(),items:{}};for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(k&&k.startsWith('cc-'))backup.items[k]=localStorage.getItem(k)}const blob=new Blob([JSON.stringify(backup,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='crawler-companion-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}}
function show(){render();ensurePanel().style.display='block';const m=document.querySelector('.app>main') as HTMLElement|null;if(m)m.style.display='none';document.getElementById('cc-character-dashboard-v2')?.setAttribute('data-visible','false');document.body.dataset.ccPrimaryTab='character-wizard'}
function hide(){const p=document.getElementById(ID);if(p)p.style.display='none';const m=document.querySelector('.app>main') as HTMLElement|null;if(m)m.style.display=''}
function dedupe(){document.querySelectorAll<HTMLImageElement>('.character-bar img[src*="app-icon.svg"],#cc-character-dashboard-v2 .cc2-mini[src*="app-icon.svg"]').forEach(x=>x.style.display='none')}
function install(){const nav=document.querySelector('[aria-label="Primary navigation"]') as HTMLElement|null;if(!nav)return;nav.style.display='flex';nav.style.visibility='visible';if(!document.getElementById(BTN)){const b=document.createElement('button');b.id=BTN;b.type='button';b.textContent='Character Wizard';b.onclick=e=>{e.preventDefault();e.stopPropagation();nav.querySelectorAll('button').forEach(x=>{x.classList.remove('active');x.removeAttribute('aria-current')});b.classList.add('active');b.setAttribute('aria-current','page');show()};const character=[...nav.querySelectorAll('button')].find(x=>(x.textContent||'').replace(/✦/g,'').trim().toLowerCase()==='character');if(character)character.insertAdjacentElement('afterend',b);else nav.prepend(b);nav.addEventListener('click',e=>{const t=(e.target as Element)?.closest('button');if(t&&t!==b)hide()},true)}dedupe();setTimeout(()=>{const dice=document.querySelector('#cc-character-dashboard-v2 .cc2-dice');if(dice){(dice as HTMLElement).dataset.ccDiceUpgraded='';upgradeCharacterDice()}},50)}
let n=0;const timer=setInterval(()=>{n++;install();if(document.getElementById(BTN)||n>40)clearInterval(timer)},100);document.addEventListener('click',()=>setTimeout(()=>{dedupe();upgradeCharacterDice()},80),true);if(document.readyState!=='loading')setTimeout(install,0);else document.addEventListener('DOMContentLoaded',()=>setTimeout(install,0),{once:true});
export {install as installCharacterWizard};