const ID='cc-character-sheet-spells';
const SPELLS:any[]=[
{name:'Heal',mana:2},{name:'Fire Fingers',mana:3},{name:'Frost Scar',mana:2},{name:'Magic Missile',mana:5},{name:'Drain Life',mana:14},{name:'Heal Others',mana:6},{name:'Heal Critter',mana:8},{name:'Heal Self',mana:1},{name:'Holy Aura',mana:7},{name:'Hot Stuff Aura',mana:8},{name:'Ice Blast',mana:9},{name:'Icicles',mana:19},{name:'Intimate Touches',mana:8},{name:'Lightning Bolt',mana:15},{name:'Hole',mana:12}
];
function activeName(){return document.querySelector('#cc-character-dashboard-v2 .cc2-name')?.textContent?.trim()||document.querySelector('.character-bar select option:checked')?.textContent?.trim()||'Crawler'}
function stateKey(){return `cc-spell-state:${activeName()}`}
function load(){try{return JSON.parse(localStorage.getItem(stateKey())||'{}')}catch{return {}}}
function save(s:any){localStorage.setItem(stateKey(),JSON.stringify(s));window.dispatchEvent(new CustomEvent('cc-resource-change',{detail:{kind:'mana',current:Number(s.currentMana||0),max:Number(s.maxMana||0),character:activeName()}}))}
function mount(){const root=document.getElementById('cc-character-dashboard-v2');if(!root||root.getAttribute('data-visible')!=='true')return;const main=root.querySelector('.cc2-main');if(!main)return;let box=document.getElementById(ID) as HTMLElement|null;if(!box){box=document.createElement('section');box.id=ID;box.className='cc2-panel';box.style.cssText='padding:14px';main.appendChild(box)}const s=load();const known=Array.isArray(s.known)?s.known:[];const current=Number(s.currentMana??s.maxMana??10);const max=Number(s.maxMana||10);box.innerHTML=`<div class="cc2-title">✨ SPELLS</div><div style="margin-bottom:10px">Mana: <b>${current} / ${max}</b></div><div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:8px">${known.length?known.map((n:string)=>{const sp=SPELLS.find(x=>x.name===n)||{name:n,mana:0};return `<div style="border:1px solid #4a3a27;border-radius:9px;padding:10px;background:#101722"><b>${sp.name}</b><div>${sp.mana} Mana</div><button type="button" data-cast="${sp.name}" data-cost="${sp.mana}" ${current<sp.mana?'disabled':''} style="margin-top:7px">Cast</button></div>`}).join(''):'<div>No known spells yet.</div>'}</div>`;box.querySelectorAll<HTMLButtonElement>('[data-cast]').forEach(b=>b.onclick=()=>{const st=load();const cost=Number(b.dataset.cost||0);const cur=Number(st.currentMana??st.maxMana??10);if(cur<cost)return;st.maxMana=Number(st.maxMana||10);st.currentMana=Math.max(0,cur-cost);save(st);mount()})}
function q(){setTimeout(mount,80)}
document.addEventListener('click',e=>{if((e.target as Element)?.closest('[aria-label="Primary navigation"],.character-bar'))q()},true);window.addEventListener('cc-resource-change',q);window.addEventListener('cc:character-updated',q);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(mount,700),{once:true});else setTimeout(mount,700);
export {mount as mountCharacterSheetSpells};