const ID='cc-character-hotbar';
const STYLE='cc-character-hotbar-style';
const KEY='cc-hotbar:';
const SPELL='cc-spell-state:';

type Slot={type:'empty'|'attack'|'ability'|'spell'|'item';name:string;icon:string;cost?:number;qty?:number};
const defaults:Slot[]=[{type:'attack',name:'Attack',icon:'⚔️'},{type:'ability',name:'Ability',icon:'✦'},{type:'spell',name:'Heal',icon:'✨',cost:2},{type:'item',name:'Potion',icon:'🧪',qty:1},...Array.from({length:4},()=>({type:'empty',name:'Empty',icon:'＋'} as Slot))];
function activeName(){return document.querySelector('#cc-character-dashboard-v2 .cc2-name')?.textContent?.trim()||document.querySelector('.character-bar select option:checked')?.textContent?.trim()||'Crawler'}
function k(){return KEY+encodeURIComponent(activeName())} function sk(){return SPELL+activeName()}
function load():Slot[]{try{const v=JSON.parse(localStorage.getItem(k())||'null');return Array.isArray(v)&&v.length===8?v:structuredClone(defaults)}catch{return structuredClone(defaults)}}
function save(v:Slot[]){localStorage.setItem(k(),JSON.stringify(v))}
function spellState(){try{return JSON.parse(localStorage.getItem(sk())||'{}')}catch{return {}}}
function visibleMana(){const root=document.getElementById('cc-character-dashboard-v2');const rows=[...(root?.querySelectorAll('.cc2-resrow')||[])];const row=rows.find(r=>/mana/i.test(r.textContent||''));const text=row?.textContent||'';const m=text.match(/(\d+)\s*\/\s*(\d+)/);return m?{current:Number(m[1]),max:Number(m[2])}:null}
function normalizedSpellState(){const st=spellState();const vm=visibleMana();if(vm&&(Number(st.maxMana||0)<=0||Number(st.currentMana||0)!==vm.current)){st.maxMana=vm.max;st.currentMana=vm.current;localStorage.setItem(sk(),JSON.stringify(st))}return st}
function writeSpell(s:any){localStorage.setItem(sk(),JSON.stringify(s));window.dispatchEvent(new CustomEvent('cc-resource-change',{detail:{kind:'mana',current:Number(s.currentMana||0),max:Number(s.maxMana||0),character:activeName()}}))}
function style(){if(document.getElementById(STYLE))return;const s=document.createElement('style');s.id=STYLE;s.textContent=`#cc-character-dashboard-v2 .cc2-res{width:100%!important;grid-column:1/-1!important}#cc-character-dashboard-v2 .cc2-resrow{grid-template-columns:84px minmax(0,1fr) 74px!important}#cc-character-dashboard-v2 .cc2-track{height:32px!important;gap:6px!important;grid-template-columns:repeat(10,minmax(18px,1fr))!important}#cc-character-dashboard-v2 .cc2-seg{min-height:32px!important;border-radius:5px!important}#${ID}{padding:13px!important;grid-column:1/-1}.cc-hot-head{display:flex;align-items:center;justify-content:space-between;gap:10px;margin-bottom:9px}.cc-hot-grid{display:grid;grid-template-columns:repeat(8,minmax(72px,1fr));gap:7px}.cc-hot-slot{position:relative;min-height:84px;padding:8px 5px;border-radius:10px;border:1px solid #5a4630;background:#101722;color:#fff;text-align:center;touch-action:manipulation}.cc-hot-slot b{display:block;font-size:25px}.cc-hot-slot small{display:block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.cc-hot-meta{font-size:11px;color:#e2b968;min-height:15px}.cc-hot-edit{border:1px solid #b98538;background:#17130e;color:#ffe3a0;border-radius:8px;padding:7px 10px}.cc-hot-slot[data-empty="1"]{opacity:.65;border-style:dashed}@media(max-width:760px){.cc-hot-grid{display:flex;overflow-x:auto;padding-bottom:4px}.cc-hot-slot{min-width:76px}#cc-character-dashboard-v2 .cc2-track{height:28px!important;gap:4px!important}}`;document.head.appendChild(s)}
function knownSpells(){const st=normalizedSpellState();return Array.isArray(st.known)?st.known:[]}
function spellCost(name:string){const c:Record<string,number>={Heal:2,'Fire Fingers':3,'Frost Scar':2,'Magic Missile':5,'Drain Life':14,'Heal Others':6,'Heal Critter':8,'Heal Self':1,'Holy Aura':7,'Hot Stuff Aura':8,'Ice Blast':9,Icicles:19,'Intimate Touches':8,'Lightning Bolt':15,Hole:12};return c[name]||0}
function editSlot(i:number){const slots=load(),current=slots[i];const type=(prompt('Slot type: attack, ability, spell, item, empty',current.type)||current.type).toLowerCase() as Slot['type'];if(!['attack','ability','spell','item','empty'].includes(type))return;if(type==='empty'){slots[i]={type:'empty',name:'Empty',icon:'＋'};save(slots);render();return}let name=current.name;if(type==='spell'){const list=knownSpells();name=prompt(`Spell name${list.length?` (${list.join(', ')})`:''}`,list.includes(current.name)?current.name:(list[0]||current.name))||current.name}else name=prompt('Slot name',current.name)||current.name;const icon=prompt('Icon/emoji',current.icon)||current.icon;const next:Slot={type,name,icon};if(type==='spell')next.cost=spellCost(name);if(type==='item')next.qty=Math.max(0,Number(prompt('Quantity',String(current.qty??1))||1));slots[i]=next;save(slots);render()}
function activate(i:number){const slots=load(),x=slots[i];if(x.type==='empty'){editSlot(i);return}if(x.type==='spell'){const st=normalizedSpellState(),cost=x.cost??spellCost(x.name);const cur=Number(st.currentMana??0);if(cur<cost){alert(`Not enough Mana for ${x.name}.`);return}st.currentMana=cur-cost;writeSpell(st);window.dispatchEvent(new CustomEvent('cc:hotbar-action',{detail:{type:'spell',name:x.name,cost,character:activeName()}}));render();return}if(x.type==='item'){const qty=Number(x.qty??0);if(qty<=0){alert(`${x.name} is empty.`);return}x.qty=qty-1;slots[i]=x;save(slots);window.dispatchEvent(new CustomEvent('cc:hotbar-action',{detail:{type:'item',name:x.name,character:activeName()}}));render();return}window.dispatchEvent(new CustomEvent('cc:hotbar-action',{detail:{type:x.type,name:x.name,character:activeName()}}));const btn=[...document.querySelectorAll<HTMLButtonElement>('#cc-character-dashboard-v2 button')].find(b=>(b.textContent||'').trim().toLowerCase().includes(x.name.toLowerCase()));btn?.click()}
function render(){style();const root=document.getElementById('cc-character-dashboard-v2');if(!root||root.dataset.visible!=='true')return;let box=document.getElementById(ID) as HTMLElement|null;if(!box){box=document.createElement('section');box.id=ID;box.className='cc2-panel';const main=root.querySelector('.cc2-main');const hero=main?.querySelector('.cc2-hero');if(hero)hero.insertAdjacentElement('afterend',box);else main?.prepend(box)}const slots=load(),st=normalizedSpellState();box.innerHTML=`<div class="cc-hot-head"><div class="cc2-title">🔥 HOTBAR / LOADOUT</div><button class="cc-hot-edit" type="button">Edit Loadout</button></div><div class="cc-hot-grid">${slots.map((x,i)=>`<button class="cc-hot-slot" type="button" data-i="${i}" data-empty="${x.type==='empty'?'1':'0'}"><b>${x.icon}</b><small>${i+1}. ${x.name}</small><span class="cc-hot-meta">${x.type==='spell'?`${x.cost??spellCost(x.name)} MP • ${Number(st.currentMana??0)} left`:x.type==='item'?`${Number(x.qty??0)} left`:x.type==='empty'?'assign slot':x.type}</span></button>`).join('')}</div>`;box.querySelectorAll<HTMLButtonElement>('[data-i]').forEach(b=>{const i=Number(b.dataset.i);b.onclick=()=>activate(i);b.oncontextmenu=e=>{e.preventDefault();editSlot(i)}});box.querySelector<HTMLButtonElement>('.cc-hot-edit')!.onclick=()=>{const n=Number(prompt('Edit which slot? 1-8','1')||0);if(n>=1&&n<=8)editSlot(n-1)}}
function q(){setTimeout(render,80)} window.addEventListener('cc-resource-change',q);window.addEventListener('cc:character-updated',q);window.addEventListener('cc:campaign-changed',q);document.addEventListener('click',e=>{if((e.target as Element)?.closest('[aria-label="Primary navigation"],.character-bar'))q()},true);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(render,900),{once:true});else setTimeout(render,900);export {render as renderCharacterHotbar};