const ID='cc-character-hotbar';
const STYLE='cc-character-hotbar-style';
const KEY='cc-hotbar:';
const SPELL='cc-spell-state:';

type Slot={type:'empty'|'spell'|'item'|'weapon';name:string;icon:string;cost?:number;qty?:number};
const empty=():Slot=>({type:'empty',name:'Empty',icon:'＋'});
const defaults:Slot[]=[{type:'spell',name:'Heal',icon:'✨',cost:2},{type:'item',name:'Potion',icon:'🧪',qty:1},...Array.from({length:8},empty)];
function activeName(){return document.querySelector('#cc-character-dashboard-v2 .cc2-name')?.textContent?.trim()||document.querySelector('.character-bar select option:checked')?.textContent?.trim()||'Crawler'}
function k(){return KEY+encodeURIComponent(activeName())} function sk(){return SPELL+activeName()}
function load():Slot[]{try{const v=JSON.parse(localStorage.getItem(k())||'null');if(Array.isArray(v)){const cleaned=v.filter((x:any)=>!['attack','ability'].includes(String(x?.type||''))).map((x:any)=>x as Slot);while(cleaned.length<10)cleaned.push(empty());return cleaned.slice(0,10)}return structuredClone(defaults)}catch{return structuredClone(defaults)}}
function save(v:Slot[]){localStorage.setItem(k(),JSON.stringify(v.slice(0,10)))}
function spellState(){try{return JSON.parse(localStorage.getItem(sk())||'{}')}catch{return {}}}
function visibleMana(){const rows=[...(document.querySelectorAll('#cc-character-dashboard-v2 .cc2-resrow')||[])];const row=rows.find(r=>/mana/i.test(r.textContent||''));const m=(row?.textContent||'').match(/(\d+)\s*\/\s*(\d+)/);return m?{current:Number(m[1]),max:Number(m[2])}:null}
function normalizedSpellState(){const st=spellState();const vm=visibleMana();if(vm&&(Number(st.maxMana||0)<=0||Number(st.currentMana||0)!==vm.current)){st.maxMana=vm.max;st.currentMana=vm.current;localStorage.setItem(sk(),JSON.stringify(st))}return st}
function writeSpell(s:any){localStorage.setItem(sk(),JSON.stringify(s));window.dispatchEvent(new CustomEvent('cc-resource-change',{detail:{kind:'mana',current:Number(s.currentMana||0),max:Number(s.maxMana||0),character:activeName()}}))}
function toast(msg:string){let t=document.getElementById('cc-hot-toast');if(!t){t=document.createElement('div');t.id='cc-hot-toast';document.body.appendChild(t)}t.textContent=msg;t.className='show';setTimeout(()=>t.className='',1500)}
function style(){if(document.getElementById(STYLE))return;const s=document.createElement('style');s.id=STYLE;s.textContent=`#cc-character-dashboard-v2 .cc2-res{width:100%!important;grid-column:1/-1!important}#cc-character-dashboard-v2 .cc2-resrow{grid-template-columns:84px minmax(0,1fr) 74px!important}#cc-character-dashboard-v2 .cc2-track{height:32px!important;gap:6px!important;grid-template-columns:repeat(10,minmax(18px,1fr))!important}#cc-character-dashboard-v2 .cc2-seg{min-height:32px!important;border-radius:5px!important}#${ID}{padding:13px!important;grid-column:1/-1}.cc-hot-head{display:flex;align-items:center;justify-content:space-between;gap:10px;margin-bottom:9px}.cc-hot-hint{font-size:11px;color:#b8a98f}.cc-hot-grid{display:grid;grid-template-columns:repeat(10,minmax(64px,1fr));gap:6px}.cc-hot-slot{position:relative;min-height:84px;padding:8px 4px;border-radius:10px;border:1px solid #5a4630;background:#101722;color:#fff;text-align:center;touch-action:manipulation;user-select:none}.cc-hot-slot b{display:block;font-size:25px}.cc-hot-slot small{display:block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.cc-hot-meta{display:block;font-size:11px;color:#e2b968;min-height:15px}.cc-hot-slot[data-empty="1"]{opacity:.65;border-style:dashed}#cc-hot-toast{position:fixed;left:50%;bottom:24px;transform:translate(-50%,20px);opacity:0;pointer-events:none;z-index:99999;background:#101722;border:1px solid #d69c42;color:#fff2ca;padding:10px 14px;border-radius:9px;transition:.18s}#cc-hot-toast.show{opacity:1;transform:translate(-50%,0)}@media(max-width:900px){.cc-hot-grid{display:flex;overflow-x:auto;padding-bottom:5px}.cc-hot-slot{min-width:76px}}@media(max-width:760px){#cc-character-dashboard-v2 .cc2-track{height:28px!important;gap:4px!important}}`;document.head.appendChild(s)}
function knownSpells(){const st=normalizedSpellState();return Array.isArray(st.known)?st.known:[]}
function spellCost(name:string){const c:Record<string,number>={Heal:2,'Fire Fingers':3,'Frost Scar':2,'Magic Missile':5,'Drain Life':14,'Heal Others':6,'Heal Critter':8,'Heal Self':1,'Holy Aura':7,'Hot Stuff Aura':8,'Ice Blast':9,Icicles:19,'Intimate Touches':8,'Lightning Bolt':15,Hole:12};return c[name]||0}
function editSlot(i:number){const slots=load(),current=slots[i]||empty();const type=(prompt('Slot type: spell, potion/item, weapon, empty',current.type==='item'?'item':current.type)||current.type).toLowerCase() as Slot['type'];if(!['spell','item','weapon','empty'].includes(type))return;if(type==='empty'){slots[i]=empty();save(slots);render();return}let name=current.name==='Empty'?'':current.name;if(type==='spell'){const list=knownSpells();name=prompt(`Spell${list.length?` (${list.join(', ')})`:''}`,list.includes(name)?name:(list[0]||name||'Heal'))||name||'Heal'}else name=prompt(type==='weapon'?'Weapon name':'Potion / item name',name||type)||name||type;const icon=prompt('Icon/emoji',current.type===type?current.icon:(type==='weapon'?'⚔️':type==='item'?'🧪':'✨'))||current.icon;const next:Slot={type,name,icon};if(type==='spell')next.cost=spellCost(name);if(type==='item')next.qty=Math.max(0,Number(prompt('Quantity',String(current.qty??1))||1));slots[i]=next;save(slots);render()}
function activate(i:number){const slots=load(),x=slots[i];if(!x||x.type==='empty'){editSlot(i);return}if(x.type==='spell'){const st=normalizedSpellState(),cost=x.cost??spellCost(x.name),cur=Number(st.currentMana??0);if(cur<cost){toast(`Not enough Mana for ${x.name}`);return}st.currentMana=cur-cost;writeSpell(st);window.dispatchEvent(new CustomEvent('cc:hotlist-action',{detail:{type:'spell',name:x.name,cost,character:activeName()}}));toast(`${x.name} cast • ${cost} MP`);render();return}if(x.type==='item'){const qty=Number(x.qty??0);if(qty<=0){toast(`${x.name} is empty`);return}x.qty=qty-1;slots[i]=x;save(slots);const detail={type:'item',name:x.name,character:activeName(),remaining:x.qty};window.dispatchEvent(new CustomEvent('cc:consume-item',{detail}));window.dispatchEvent(new CustomEvent('cc:hotlist-action',{detail}));toast(`${x.name} used • ${x.qty} left`);render();return}if(x.type==='weapon'){const detail={type:'weapon',name:x.name,character:activeName()};window.dispatchEvent(new CustomEvent('cc:equip-weapon',{detail}));window.dispatchEvent(new CustomEvent('cc:hotlist-action',{detail}));toast(`${x.name} selected`);return}}
function bindSlot(b:HTMLButtonElement,i:number){let timer:any=null,long=false;b.onclick=e=>{if(long){long=false;e.preventDefault();return}activate(i)};b.oncontextmenu=e=>{e.preventDefault();editSlot(i)};b.onpointerdown=()=>{long=false;timer=setTimeout(()=>{long=true;editSlot(i)},550)};const cancel=()=>{if(timer)clearTimeout(timer)};b.onpointerup=cancel;b.onpointercancel=cancel;b.onpointerleave=cancel}
function render(){style();const root=document.getElementById('cc-character-dashboard-v2');if(!root||root.dataset.visible!=='true')return;let box=document.getElementById(ID) as HTMLElement|null;if(!box){box=document.createElement('section');box.id=ID;box.className='cc2-panel';const hero=root.querySelector('.cc2-main .cc2-hero');if(hero)hero.insertAdjacentElement('afterend',box);else root.querySelector('.cc2-main')?.prepend(box)}const slots=load();save(slots);const st=normalizedSpellState();box.innerHTML=`<div class="cc-hot-head"><div class="cc2-title">🔥 HOTLIST</div><div class="cc-hot-hint">Tap to use • long-press to edit</div></div><div class="cc-hot-grid">${slots.map((x,i)=>`<button class="cc-hot-slot" type="button" data-i="${i}" data-empty="${x.type==='empty'?'1':'0'}" title="${x.type==='empty'?'Assign slot':x.name}"><b>${x.icon}</b><small>${i+1}. ${x.name}</small><span class="cc-hot-meta">${x.type==='spell'?`${x.cost??spellCost(x.name)} MP • ${Number(st.currentMana??0)} left`:x.type==='item'?`${Number(x.qty??0)} left`:x.type==='weapon'?'tap to equip':'tap to assign'}</span></button>`).join('')}</div>`;box.querySelectorAll<HTMLButtonElement>('[data-i]').forEach(b=>bindSlot(b,Number(b.dataset.i)))}
function q(){setTimeout(render,80)}window.addEventListener('cc-resource-change',q);window.addEventListener('cc:character-updated',q);window.addEventListener('cc:campaign-changed',q);document.addEventListener('click',e=>{if((e.target as Element)?.closest('[aria-label="Primary navigation"],.character-bar'))q()},true);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(render,900),{once:true});else setTimeout(render,900);export {render as renderCharacterHotbar};