const ID='cc-character-dashboard-v2';
const STYLE='cc-character-dashboard-v2-style';
const THEME_KEY='cc-sheet-theme:';
const PORTRAIT_KEY='cc-character-portrait:';

const themes:any={
 'Ginger Fire':{a:'#f5b33b',b:'#ff4a19',c:'#7b170f',glow:'rgba(255,88,26,.35)'},
 'Arcane Purple':{a:'#b86cff',b:'#7a37ff',c:'#301050',glow:'rgba(147,73,255,.35)'},
 'Frost Blue':{a:'#62d9ff',b:'#188cff',c:'#0b3154',glow:'rgba(58,171,255,.35)'},
 'Emerald Green':{a:'#61f0a0',b:'#12b968',c:'#0c4730',glow:'rgba(32,210,116,.32)'},
 'Shadow Grey':{a:'#d1d7df',b:'#7d8797',c:'#252a31',glow:'rgba(180,190,205,.22)'},
 'Sunset Orange':{a:'#ffd06b',b:'#ff7a24',c:'#6b2b13',glow:'rgba(255,137,42,.34)'}
};

function activeTab(){const n=document.querySelector('[aria-label="Primary navigation"]');const b=n?.querySelector('button.active,[aria-current="page"]') as HTMLElement|null;return (b?.textContent||'').replace(/✦/g,'').trim()}
function activeName(){const bar=document.querySelector('.character-bar');const s=bar?.querySelector('select option:checked')?.textContent?.trim();if(s)return s;return 'Crawler'}
function keyName(n:string){return encodeURIComponent(n||'Crawler')}
function readTheme(n:string){return localStorage.getItem(THEME_KEY+keyName(n))||'Ginger Fire'}
function readPortrait(n:string){return localStorage.getItem(PORTRAIT_KEY+keyName(n))||''}
function esc(s:any){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'} as any)[m])}
function text(re:RegExp,def='—'){const t=document.querySelector('.app>main')?.textContent||'';const m=t.match(re);return m?.[1]?.trim()||def}
function stat(label:string,def='10'){return text(new RegExp(`${label}\\s*[:]?\\s*(\\d+)`,'i'),def)}
function level(){return text(/Level\s*[:]?\s*(\d+)/i,'1')}
function race(){return text(/Race\s*[:]?\s*([A-Za-z][A-Za-z '\-]+)/i,'Human').split(/\n|Class|Level|Background/i)[0].trim()}
function klass(){return text(/Class\s*[:]?\s*([A-Za-z][A-Za-z '\-]+)/i,'Crawler').split(/\n|Race|Level|Background/i)[0].trim()}
function addStyles(){if(document.getElementById(STYLE))return;const s=document.createElement('style');s.id=STYLE;s.textContent=`
 #${ID}{--a:#f5b33b;--b:#ff4a19;--c:#7b170f;--glow:rgba(255,88,26,.35);display:none;margin:0 18px 24px;color:#f8ead0}
 #${ID}[data-visible="true"]{display:grid;grid-template-columns:minmax(190px,250px) minmax(0,1fr) minmax(235px,310px);gap:12px}
 #${ID} *{box-sizing:border-box}
 #${ID} .cc2-panel{background:linear-gradient(180deg,rgba(10,15,22,.98),rgba(7,11,17,.98));border:1px solid color-mix(in srgb,var(--a) 55%,#2d3542);border-radius:13px;box-shadow:0 8px 28px rgba(0,0,0,.3),0 0 20px var(--glow)}
 #${ID} .cc2-side{padding:12px;align-self:start}
 #${ID} .cc2-title{font-family:Georgia,serif;color:var(--a);font-size:15px;font-weight:800;letter-spacing:.04em;margin-bottom:9px}
 #${ID} .cc2-charlist{display:grid;gap:7px}.cc2-char{display:flex;gap:8px;align-items:center;padding:9px;border:1px solid #37414e;border-radius:10px;background:#121924}.cc2-char.active{border-color:var(--a);box-shadow:0 0 14px var(--glow)}
 #${ID} .cc2-mini{width:42px;height:42px;border-radius:8px;object-fit:cover;background:#151b24;border:1px solid #4b5563}
 #${ID} .cc2-subnav{display:grid;gap:6px;margin-top:12px}.cc2-subnav button{width:100%;text-align:left;background:#111821;border:1px solid #303947;color:#e8e2d8;padding:8px 9px;border-radius:8px}.cc2-subnav button.active{background:linear-gradient(90deg,var(--c),#151922);border-color:var(--a);color:#fff}
 #${ID} .cc2-main{display:grid;gap:12px;align-self:start}
 #${ID} .cc2-hero{padding:12px;display:grid;grid-template-columns:220px minmax(0,1fr);gap:14px}
 #${ID} .cc2-portrait-wrap{position:relative;border:1px solid var(--a);border-radius:12px;padding:6px;background:#0d1118;box-shadow:0 0 20px var(--glow)}
 #${ID} .cc2-portrait{width:100%;aspect-ratio:4/5;object-fit:cover;border-radius:9px;background:radial-gradient(circle at 50% 20%,var(--c),#080b11 70%)}
 #${ID} .cc2-upload{display:block;width:100%;margin-top:6px;text-align:center;padding:8px;border:1px solid var(--a);border-radius:8px;cursor:pointer;background:#17130e;color:#ffe6b3;font-weight:800}.cc2-upload input{display:none}
 #${ID} .cc2-head{display:flex;align-items:flex-start;justify-content:space-between;gap:10px}.cc2-name{font-family:Georgia,serif;font-size:38px;line-height:1;color:#fff}.cc2-meta{opacity:.88;font-size:17px;margin-top:7px}.cc2-theme{background:#0d1420;border:1px solid var(--a);color:#f8ead0;padding:8px 10px;border-radius:8px}
 #${ID} .cc2-res{display:grid;gap:9px;margin:14px 0}.cc2-resrow{display:grid;grid-template-columns:78px minmax(0,1fr) 70px;gap:8px;align-items:center}.cc2-track{display:grid;grid-template-columns:repeat(10,1fr);gap:4px;height:24px}.cc2-seg{border:1px solid #384454;border-radius:4px;background:#141b25}.cc2-seg.hp.on{background:linear-gradient(#ff5d4a,#ba221b);border-color:#ff705c}.cc2-seg.mp.on{background:linear-gradient(#2fd3ff,#1674dd);border-color:#57ddff}.cc2-reslabel{font-weight:800}.cc2-resval{text-align:right;font-weight:800}
 #${ID} .cc2-stats{display:grid;grid-template-columns:repeat(6,1fr);gap:7px}.cc2-stat{padding:10px 6px;text-align:center;border:1px solid var(--a);border-radius:9px;background:linear-gradient(180deg,#151b23,#0c1118)}.cc2-stat b{display:block;color:var(--a);font-size:13px}.cc2-stat strong{display:block;font-size:24px;margin:3px 0}
 #${ID} .cc2-cards{display:grid;grid-template-columns:1fr 1fr;gap:12px}.cc2-card{padding:14px}.cc2-card h3{margin:0 0 8px;font-family:Georgia,serif;color:var(--a);font-size:21px}.cc2-card p{margin:0;line-height:1.45;color:#d8dbe1}
 #${ID} .cc2-bottom{display:grid;grid-template-columns:minmax(0,1fr) 220px;gap:12px}.cc2-skills{padding:13px}.cc2-skills-grid{display:grid;grid-template-columns:repeat(5,1fr);gap:8px}.cc2-skill{padding:9px 5px;text-align:center;border:1px solid #394657;border-radius:9px;background:#101722}.cc2-skill span{display:grid;place-items:center;width:54px;height:54px;margin:0 auto 6px;border-radius:9px;background:radial-gradient(circle,var(--c),#0a0f17 70%);font-size:26px;border:1px solid var(--a)}
 #${ID} .cc2-cond{padding:13px}.cc2-cond label{display:block;margin:8px 0;color:#e5e8ee}
 #${ID} .cc2-right{display:grid;gap:12px;align-self:start}.cc2-dice,.cc2-quick,.cc2-recent{padding:13px}.cc2-diebuttons{display:grid;grid-template-columns:repeat(6,1fr);gap:6px}.cc2-diebuttons button,.cc2-roll{background:#111925;border:1px solid #465365;color:#eef2f8;padding:9px 6px;border-radius:8px}.cc2-roll{width:100%;margin-top:9px;background:linear-gradient(135deg,var(--c),var(--b));border-color:var(--a);font-weight:900;font-size:17px}.cc2-result{text-align:center;font-size:30px;font-weight:900;color:var(--a);min-height:38px;margin-top:9px}.cc2-quickgrid{display:grid;grid-template-columns:1fr 1fr;gap:7px}.cc2-quickgrid button{padding:10px 7px;border-radius:8px;border:1px solid var(--a);background:#121923;color:#fff}.cc2-recent ol{margin:8px 0 0;padding-left:24px}.cc2-recent li{padding:4px 0;border-bottom:1px solid #202a35}
 #${ID} .cc2-banner{grid-column:1/-1;min-height:132px;display:grid;grid-template-columns:minmax(0,1fr) 260px;align-items:center;padding:18px 26px;background:radial-gradient(circle at 75% 40%,rgba(255,69,17,.3),transparent 35%),linear-gradient(90deg,#180d08,#07101a 66%);border:1px solid #b56b20;border-radius:14px;overflow:hidden;position:relative}.cc2-banner::after{content:"";position:absolute;right:0;top:-45px;width:260px;height:260px;background:url('/brand/app-icon.svg') center/contain no-repeat;filter:drop-shadow(0 0 18px rgba(255,90,22,.35));opacity:.95}.cc2-brand{position:relative;z-index:2}.cc2-brand h1{font-family:Georgia,serif;font-size:38px;margin:0;color:#ffd274;text-shadow:0 2px 12px rgba(255,92,24,.45)}.cc2-brand div{font-family:Georgia,serif;letter-spacing:.24em;font-size:17px;margin-top:6px}.cc2-brand small{display:block;margin-top:7px;letter-spacing:.18em;color:#e7b664}
 @media(max-width:1050px){#${ID}[data-visible="true"]{grid-template-columns:190px minmax(0,1fr)}#${ID} .cc2-right{grid-column:1/-1;grid-template-columns:repeat(3,1fr)}#${ID} .cc2-banner{grid-column:1/-1}}
 @media(max-width:760px){#${ID}{margin:0 8px 18px}#${ID}[data-visible="true"]{display:block}#${ID} .cc2-banner{display:block;min-height:118px;margin-bottom:10px;padding:15px}.cc2-banner::after{width:150px;height:150px;top:-10px;opacity:.55}.cc2-brand h1{font-size:26px;max-width:70%}#${ID} .cc2-side{display:none}#${ID} .cc2-main,#${ID} .cc2-right{display:grid;margin-bottom:10px}#${ID} .cc2-hero{grid-template-columns:110px minmax(0,1fr);padding:10px}.cc2-name{font-size:27px}.cc2-meta{font-size:13px}.cc2-stats{grid-template-columns:repeat(3,1fr)}.cc2-cards,.cc2-bottom{grid-template-columns:1fr}.cc2-skills-grid{grid-template-columns:repeat(3,1fr)}#${ID} .cc2-right{grid-template-columns:1fr}.cc2-resrow{grid-template-columns:60px minmax(0,1fr) 54px}.cc2-track{height:19px;gap:2px}}
 `;document.head.appendChild(s)}

function segs(cls:string,on:number){return Array.from({length:10},(_,i)=>`<i class="cc2-seg ${cls} ${i<on?'on':''}"></i>`).join('')}
function make(){addStyles();let root=document.getElementById(ID) as HTMLElement|null;if(root)return root;root=document.createElement('section');root.id=ID;root.dataset.visible='false';const anchor=document.querySelector('.app>nav')||document.querySelector('.character-bar');if(anchor)anchor.insertAdjacentElement('afterend',root);else document.querySelector('.app')?.prepend(root);return root}
function setTheme(root:HTMLElement,name:string){const t=themes[name]||themes['Ginger Fire'];root.style.setProperty('--a',t.a);root.style.setProperty('--b',t.b);root.style.setProperty('--c',t.c);root.style.setProperty('--glow',t.glow)}
function render(){const root=make();if(!root)return;const show=/^Character$/i.test(activeTab());root.dataset.visible=String(show);if(!show)return;const name=activeName();const theme=readTheme(name);setTheme(root,theme);const portrait=readPortrait(name);const lvl=level(),r=race(),k=klass();const hp=7,mp=4;root.innerHTML=`
 <section class="cc2-banner cc2-panel"><div class="cc2-brand"><h1>GINGER DRAGON STUDIOS</h1><div>CRAWLER COMPANION</div><small>ADVENTURE • TRACK • SURVIVE • TOGETHER</small></div></section>
 <aside class="cc2-side cc2-panel"><div class="cc2-title">MY CHARACTERS</div><div class="cc2-charlist"><div class="cc2-char active"><img class="cc2-mini" src="${portrait||'/brand/app-icon.svg'}"><div><b>${esc(name)}</b><div>Lv ${esc(lvl)} ${esc(k)}</div></div></div></div><div class="cc2-subnav"><button class="active">👤 Character Sheet</button><button>✦ Abilities</button><button>🎒 Inventory</button><button>☰ Journal</button><button>✹ Conditions</button><button>✎ Notes</button><button>◉ Theme & Portrait</button></div></aside>
 <main class="cc2-main"><section class="cc2-hero cc2-panel"><div class="cc2-portrait-wrap"><img class="cc2-portrait" src="${portrait||'/brand/app-icon.svg'}" alt="Portrait of ${esc(name)}"><label class="cc2-upload">🖼 Change Portrait<input type="file" accept="image/*" data-cc2-file></label></div><div><div class="cc2-head"><div><div class="cc2-name">${esc(name)}</div><div class="cc2-meta">Level ${esc(lvl)} Crawler &nbsp; • &nbsp; ${esc(r)} &nbsp; • &nbsp; ${esc(k)}</div></div><select class="cc2-theme" data-cc2-theme>${Object.keys(themes).map(x=>`<option ${x===theme?'selected':''}>${x}</option>`).join('')}</select></div><div class="cc2-res"><div class="cc2-resrow"><span class="cc2-reslabel">❤️ Health</span><div class="cc2-track">${segs('hp',hp)}</div><span class="cc2-resval">${hp} / 10</span></div><div class="cc2-resrow"><span class="cc2-reslabel">✨ Mana</span><div class="cc2-track">${segs('mp',mp)}</div><span class="cc2-resval">${mp} / 10</span></div></div><div class="cc2-stats">${[['STR',stat('STR','12')],['DEX',stat('DEX','18')],['CON',stat('CON','14')],['INT',stat('INT','10')],['WIS',stat('WIS','12')],['CHA',stat('CHA','8')]].map(([a,b])=>`<div class="cc2-stat"><b>${a}</b><strong>${b}</strong><span>${Math.floor((Number(b)-10)/2)>=0?'+':''}${Math.floor((Number(b)-10)/2)}</span></div>`).join('')}</div></div></section><section class="cc2-cards"><article class="cc2-card cc2-panel"><h3>Race: ${esc(r)}</h3><p>Your ancestry, appearance, traits and race details live here. Use the Character editor to change them.</p></article><article class="cc2-card cc2-panel"><h3>Class: ${esc(k)}</h3><p>Your class features, combat role, progression and abilities are summarized here.</p></article></section><section class="cc2-bottom"><div class="cc2-skills cc2-panel"><div class="cc2-title">✦ SKILLS & ABILITIES</div><div class="cc2-skills-grid">${[['🗡','Backstab'],['🥷','Stealth'],['💨','Evasion'],['⚔','Ambush'],['🧠','Tactical Mind']].map(x=>`<div class="cc2-skill"><span>${x[0]}</span>${x[1]}</div>`).join('')}</div></div><div class="cc2-cond cc2-panel"><div class="cc2-title">☠ CONDITIONS</div>${['Poisoned','Bleeding','Stunned','Restrained','Charmed'].map(x=>`<label><input type="checkbox"> ${x}</label>`).join('')}</div></section></main>
 <aside class="cc2-right"><section class="cc2-dice cc2-panel"><div class="cc2-title">🎲 DICE ROLLER</div><div class="cc2-diebuttons">${[4,6,8,10,12,20].map(d=>`<button data-cc2-die="${d}">d${d}</button>`).join('')}</div><button class="cc2-roll" data-cc2-roll>ROLL d20</button><div class="cc2-result" data-cc2-result></div></section><section class="cc2-quick cc2-panel"><div class="cc2-title">⚡ QUICK ACTIONS</div><div class="cc2-quickgrid"><button data-cc2-rest="short">🛏 Short Rest</button><button data-cc2-rest="long">🔥 Long Rest</button><button data-cc2-heal>➕ Heal</button><button data-cc2-reset>💜 Reset HP/MP</button></div></section><section class="cc2-recent cc2-panel"><div class="cc2-title">✦ RECENT ROLLS</div><ol data-cc2-recent></ol></section></aside>`;
 const f=root.querySelector('[data-cc2-file]') as HTMLInputElement|null;f?.addEventListener('change',()=>{const file=f.files?.[0];if(!file)return;const rd=new FileReader();rd.onload=()=>{const data=String(rd.result||'');if(data.startsWith('data:image/')){localStorage.setItem(PORTRAIT_KEY+keyName(name),data);window.dispatchEvent(new CustomEvent('cc:character-portrait-updated',{detail:{name}}));render()}};rd.readAsDataURL(file)});
 (root.querySelector('[data-cc2-theme]') as HTMLSelectElement|null)?.addEventListener('change',e=>{localStorage.setItem(THEME_KEY+keyName(name),(e.target as HTMLSelectElement).value);render()});
 let die=20;root.querySelectorAll<HTMLButtonElement>('[data-cc2-die]').forEach(b=>b.onclick=()=>{die=Number(b.dataset.cc2Die||20);const rb=root.querySelector('[data-cc2-roll]') as HTMLButtonElement;rb.textContent=`ROLL d${die}`});
 (root.querySelector('[data-cc2-roll]') as HTMLButtonElement).onclick=()=>{const n=Math.floor(Math.random()*die)+1;(root.querySelector('[data-cc2-result]') as HTMLElement).textContent=String(n);const list=root.querySelector('[data-cc2-recent]') as HTMLOListElement;const li=document.createElement('li');li.textContent=`d${die}: ${n}`;list.prepend(li);while(list.children.length>5)list.lastElementChild?.remove()};
 (root.querySelector('[data-cc2-reset]') as HTMLButtonElement).onclick=()=>{window.dispatchEvent(new CustomEvent('cc-resource-change'));window.dispatchEvent(new CustomEvent('cc:character-updated'))};
 (root.querySelector('[data-cc2-heal]') as HTMLButtonElement).onclick=()=>window.dispatchEvent(new CustomEvent('cc-resource-change'));
}
function q(){setTimeout(render,40)}
document.addEventListener('click',e=>{if((e.target as Element)?.closest('[aria-label="Primary navigation"],.character-bar'))q()},true);document.addEventListener('change',e=>{if((e.target as Element)?.closest('.character-bar'))q()},true);window.addEventListener('cc:character-updated',q);window.addEventListener('cc:campaign-changed',q);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(render,350),{once:true});else setTimeout(render,350);
export { render as renderCharacterDashboardV2 };
