import React,{useEffect,useState} from 'react';
import {cloudLeaderboard,cloudLiveStats,cloudListEvents,cloudPushEvent,cloudSubscribeCampaign} from './cloud';

type Crawler={id:string;name:string;floor:number;level:number;popularity:number;aiFavor:number};
const fmt=(n:number)=>`${String(Math.floor(n/3600)).padStart(2,'0')}:${String(Math.floor(n%3600/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`;
export function DungeonLive({characters}:{characters:Crawler[]}){
 const [seconds,setSeconds]=useState(()=>Number(localStorage.getItem('cc-floor-timer-seconds')||3600));
 const [running,setRunning]=useState(()=>localStorage.getItem('cc-floor-timer-running')==='1');
 const [endAt,setEndAt]=useState(()=>Number(localStorage.getItem('cc-floor-timer-end')||0));
 const [now,setNow]=useState(Date.now()); const [board,setBoard]=useState<any[]>([]); const [stats,setStats]=useState<any>(null); const [events,setEvents]=useState<any[]>([]);
 const campaignId=localStorage.getItem('cc-active-campaign')||''; const remaining=running&&endAt?Math.max(0,Math.ceil((endAt-now)/1000)):seconds;
 useEffect(()=>{if(!running)return;const t=setInterval(()=>setNow(Date.now()),250);return()=>clearInterval(t)},[running]);
 useEffect(()=>{if(running&&endAt&&now>=endAt){setRunning(false);setSeconds(0);try{const Ctx=(window.AudioContext||(window as any).webkitAudioContext);if(Ctx){const c=new Ctx(),o=c.createOscillator(),g=c.createGain();o.connect(g);g.connect(c.destination);o.frequency.value=180;g.gain.value=.12;o.start();o.stop(c.currentTime+.7)}}catch{}}},[now,running,endAt]);
 useEffect(()=>{localStorage.setItem('cc-floor-timer-seconds',String(seconds));localStorage.setItem('cc-floor-timer-running',running?'1':'0');localStorage.setItem('cc-floor-timer-end',String(endAt))},[seconds,running,endAt]);
 useEffect(()=>{cloudLeaderboard().then(setBoard).catch(()=>setBoard([]));cloudLiveStats().then(setStats).catch(()=>setStats(null));if(campaignId){cloudListEvents(campaignId,100).then(setEvents).catch(()=>{});return cloudSubscribeCampaign(campaignId,e=>setEvents(x=>[e,...x].slice(0,100))) }},[campaignId]);
 const start=async()=>{const end=Date.now()+Math.max(0,seconds)*1000;setEndAt(end);setNow(Date.now());setRunning(true);if(campaignId)try{await cloudPushEvent(campaignId,'floor_timer',{action:'start',end_at:new Date(end).toISOString(),seconds})}catch{}};
 const pause=async()=>{setSeconds(remaining);setRunning(false);setEndAt(0);if(campaignId)try{await cloudPushEvent(campaignId,'floor_timer',{action:'pause',seconds:remaining})}catch{}};
 const reset=()=>{setRunning(false);setEndAt(0);setSeconds(3600)};
 const localBoard=[...characters].sort((a,b)=>(b.floor-a.floor)||(b.level-a.level)||(b.popularity-a.popularity)); const rows=board.length?board:localBoard.map((c,i)=>({rank:i+1,name:c.name||'Unnamed Crawler',floor:c.floor,level:c.level,popularity:c.popularity,ai_favor:c.aiFavor,local:true}));
 return <><section className="section-head"><div><h2>Dungeon Live</h2><p>Floor clock, real activity, and crawler rankings.</p></div><span className="pill">{campaignId?'Live Campaign':'Local Session'}</span></section><div className="gm-grid"><section className="card"><h3>⏳ Floor Countdown</h3><div className={`floor-clock ${remaining<=300?'danger':''}`}>{fmt(remaining)}</div><div className="buttonrow">{running?<button onClick={pause}>⏸ Pause</button>:<button onClick={start}>▶ Start</button>}<button onClick={reset}>↺ Reset 1 Hour</button><button onClick={()=>setSeconds(Math.max(0,seconds+300))}>+5 min</button><button onClick={()=>setSeconds(Math.max(0,seconds-300))}>−5 min</button></div><p className="hint">GM timer actions are recorded in the active campaign feed. Final five minutes turn red and zero triggers an alert sound.</p></section><section className="card"><h3>🟢 Actual Usage</h3><p><b>{stats?.accounts??'—'}</b> registered accounts</p><p><b>{stats?.openers??'—'}</b> unique app openers</p><p><b>{stats?.active_today??'—'}</b> active today</p><p className="hint">Cloud-backed counts only. No fake demo numbers.</p></section></div><section className="card"><h3>🏆 Crawler Leaderboard</h3>{rows.slice(0,25).map((r:any,i:number)=><div className="leader-row" key={`${r.name}-${i}`}><strong>#{r.rank||i+1} {r.name}</strong><span>Floor {r.floor||1} • Level {r.level||1} • Popularity {r.popularity||0} • AI Favor {r.ai_favor||0}{r.local?' • Local':''}</span></div>)}<p className="hint">Global rankings include only crawlers whose owners opt in. Until the cloud leaderboard is enabled, your local crawlers are shown.</p></section><section className="card"><h3>📜 Dungeon Activity Feed</h3>{events.length===0?<p className="hint">Select an online campaign to show its true running event log. Loot pushes, timer actions and campaign events appear here.</p>:events.map((e:any)=><div className="event-row" key={e.id}><b>{e.event_type==='loot'?'🎁 Loot':e.event_type==='floor_timer'?'⏳ Floor Timer':'⚡ '+e.event_type}</b><span>{new Date(e.created_at).toLocaleString()}</span><p>{e.event_type==='loot'?`${e.payload?.rarity||''} ${e.payload?.name||''} → ${e.payload?.targetName||'crawler'}`:e.event_type==='floor_timer'?`${e.payload?.action||'update'} • ${e.payload?.seconds??''} seconds`:JSON.stringify(e.payload)}</p></div>)}</section></>
}
