import { cloudListCharacters, cloudSaveCharacter } from './cloud';
const PANEL='cc-equipment-stats';
type Gear={name:string;category?:string;rarity?:string;damage?:string;defense?:number;damageResist?:number;resistType?:string;charges?:number;value?:number;equipped?:boolean;detail?:string};
const rank=(r='Bronze')=>Math.max(0,['Bronze','Silver','Gold','Epic','Legendary'].indexOf(r));
function mechanicalize(item:any):Gear{const g={...item} as Gear;const r=rank(g.rarity);if(g.category==='Weapon'){g.damage=g.damage||`${1+Math.floor(r/2)}d${6+r*2}`;g.value=g.value||25*(r+1)}if(g.category==='Armor'){g.defense=g.defense??1+r;g.damageResist=g.damageResist??Math.max(1,Math.ceil((r+1)/2));g.value=g.value||35*(r+1);if(r>=2&&!g.resistType)g.resistType=['Physical','Fire','Cold','Electric','Acid'][r%5]}if(g.category==='Consumable'){g.charges=g.charges??1;g.value=g.value||15*(r+1)}if(g.category==='Utility'){g.value=g.value||20*(r+1)}return g}
function totals(inv:Gear[]){const eq=inv.filter(x=>x.equipped);return {defense:eq.reduce((n,x)=>n+(Number(x.defense)||0),0),damageResist:eq.reduce((n,x)=>n+(Number(x.damageResist)||0),0),typed:eq.filter(x=>x.resistType&&x.damageResist).map(x=>`${x.resistType} ${x.damageResist}`)}}
async function activeChar(){const all=await cloudListCharacters() as any[];const name=document.querySelector('.character-bar button[aria-current="true"],.character-bar strong')?.textContent?.trim();return all.find(x=>x.name===name)||all[0]}
async function render(){let host=document.getElementById(PANEL);if(!host){const main=document.querySelector('main');if(!main)return;host=document.createElement('section');host.id=PANEL;host.style.cssText='margin:16px 0;padding:14px;border:1px solid rgba(230,171,82,.25);border-radius:14px';main.appendChild(host)}try{const c=await activeChar();if(!c){host.innerHTML='<h3>🛡️ Equipment & Damage Resist</h3><p>Sign in or create a crawler to manage equipment.</p>';return}const inv=(Array.isArray(c.inventory)?c.inventory:[]).map(mechanicalize);const t=totals(inv);host.innerHTML=`<h3>🛡️ Equipment & Damage Resist</h3><div style="display:flex;gap:14px;flex-wrap:wrap"><strong>Defense +${t.defense}</strong><strong>Damage Resist ${t.damageResist}</strong>${t.typed.map(x=>`<strong>${x}</strong>`).join('')}</div><div data-gear style="display:grid;gap:8px;margin-top:12px"></div>`;const list=host.querySelector('[data-gear]') as HTMLElement;inv.filter(x=>['Weapon','Armor'].includes(x.category||'')).forEach((g,i)=>{const row=document.createElement('div');row.style.cssText='padding:10px;border:1px solid rgba(255,255,255,.1);border-radius:10px';row.innerHTML=`<strong>${g.name}</strong> · ${g.rarity||''}<br><small>${g.damage?`Damage ${g.damage} · `:''}${g.defense?`Defense +${g.defense} · `:''}${g.damageResist?`Damage Resist ${g.damageResist}${g.resistType?` (${g.resistType})`:''} · `:''}${g.value?`Value ${g.value}`:''}</small> <button data-equip>${g.equipped?'Unequip':'Equip'}</button>`;(row.querySelector('[data-equip]') as HTMLButtonElement).onclick=async()=>{const original=(Array.isArray(c.inventory)?c.inventory:[]).find((x:any)=>x.name===g.name);if(original){Object.assign(original,mechanicalize(original),{equipped:!g.equipped});await cloudSaveCharacter(c);void render()}};list.appendChild(row)});if(!list.children.length)list.textContent='No equippable mechanical gear yet.'}catch(e){host.innerHTML=`<h3>🛡️ Equipment & Damage Resist</h3><p>${e instanceof Error?e.message:String(e)}</p>`}}
window.addEventListener('cc:campaign-changed',()=>void render());let wait=false;new MutationObserver(()=>{if(wait)return;wait=true;setTimeout(()=>{wait=false;void render()},400)}).observe(document.documentElement,{subtree:true,childList:true});setTimeout(()=>void render(),1500);
export { mechanicalize, totals };
