const STYLE='cc-final-ui-stability-fix-style';
const NOTE_KEY='cc-character-note:';
const JOURNAL_KEY='cc-character-journal:';
const HP_KEY='cc2-hp:';
function clean(s:string){return s.replace(/✦/g,'').replace(/^[^A-Za-z]+/,'').trim()}
function primaryNav(){return document.querySelector('[aria-label="Primary navigation"]') as HTMLElement|null}
function activeName(){return document.querySelector('#cc-character-dashboard-v2 .cc2-name')?.textContent?.trim()||document.querySelector('.character-bar select option:checked')?.textContent?.trim()||'Crawler'}
function key(p:string){return p+encodeURIComponent(activeName())}
function tabButton(name:string){return [...(primaryNav()?.querySelectorAll<HTMLButtonElement>('button')||[])].find(b=>clean(b.textContent||'').toLowerCase()===name.toLowerCase())||null}
function activatePrimary(name:string){const nav=primaryNav();if(!nav)return;nav.querySelectorAll('button').forEach(b=>{b.classList.remove('active');b.removeAttribute('aria-current')});const b=tabButton(name);if(b){b.classList.add('active');b.setAttribute('aria-current','page');b.click()}}
function placeholder(){return `data:image/svg+xml,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 400 500"><defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#24110d"/><stop offset="1" stop-color="#09111b"/></linearGradient></defs><rect width="400" height="500" fill="url(#g)"/><circle cx="200" cy="175" r="72" fill="#2c3541"/><path d="M75 455c12-110 68-165 125-165s113 55 125 165" fill="#2c3541"/><text x="200" y="475" text-anchor="middle" fill="#d8a654" font-size="22" font-family="serif">ADD PORTRAIT</text></svg>`)}`}
function badPortrait(src:string){return !src||src.includes('/brand/app-icon.svg')||src.includes('ginger-dragon-fire-full.webp')||src.startsWith('data:image/svg+xml')}
function spellState(){try{return JSON.parse(localStorage.getItem(`cc-spell-state:${activeName()}`)||'{}')}catch{return {}}}
function healthValue(){const n=Number(localStorage.getItem(key(HP_KEY)));return Number.isFinite(n)?Math.max(0,Math.min(10,n)):7}
function saveHealth(n:number){const v=Math.max(0,Math.min(10,Math.round(n)));localStorage.setItem(key(HP_KEY),String(v));window.dispatchEvent(new CustomEvent('cc-resource-change',{detail:{kind:'health',current:v,max:10,character:activeName()}}));window.dispatchEvent(new CustomEvent('cc:character-updated',{detail:{name:activeName()}}))}
function ensureTen(row:HTMLElement,cls:string){let track=row.querySelector('.cc2-track') as HTMLElement|null;if(!track)return;let segs=[...track.querySelectorAll<HTMLElement>('.cc2-seg')];if(segs.length!==10){track.innerHTML=Array.from({length:10},()=>`<i class="cc2-seg ${cls}"></i>`).join('');segs=[...track.querySelectorAll<HTMLElement>('.cc2-seg')]}}
function paintHealth(){const root=document.getElementById('cc-character-dashboard-v2');if(!root)return;const rows=[...root.querySelectorAll<HTMLElement>('.cc2-resrow')];const row=rows[0];if(!row)return;ensureTen(row,'hp');const value=healthValue();const segs=[...row.querySelectorAll<HTMLElement>('.cc2-seg')];segs.forEach((el,i)=>{el.classList.toggle('on',i<value);el.setAttribute('role','button');el.tabIndex=0;el.setAttribute('aria-label',`Set health to ${i+1} of 10`);const set=()=>saveHealth(i+1);el.onclick=set;el.onkeydown=(e)=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();set()}}});const label=row.querySelector('.cc2-resval') as HTMLElement|null;if(label)label.textContent=`${value} / 10`;let ctrl=row.querySelector('.cc2-resctrl') as HTMLElement|null;if(ctrl){const minus=ctrl.querySelector('[data-minus]') as HTMLButtonElement|null;const plus=ctrl.querySelector('[data-plus]') as HTMLButtonElement|null;if(minus)minus.onclick=()=>saveHealth(value-1);if(plus)plus.onclick=()=>saveHealth(value+1)}}
function paintMana(){const root=document.getElementById('cc-character-dashboard-v2');if(!root)return;const rows=[...root.querySelectorAll<HTMLElement>('.cc2-resrow')];const row=rows[1];if(!row)return;ensureTen(row,'mp');const st=spellState();const max=Math.max(1,Number(st.maxMana||10)||10);const cur=Math.max(0,Math.min(max,Number(st.currentMana??max)));const slots=Math.max(0,Math.min(10,Math.ceil(cur/max*10)));row.querySelectorAll<HTMLElement>('.cc2-seg').forEach((el,i)=>el.classList.toggle('on',i<slots));const label=row.querySelector('.cc2-resval') as HTMLElement|null;if(label)label.textContent=`${cur} / ${max}`}
function showEditor(kind:'notes'|'journal'){const root=document.getElementById('cc-character-dashboard-v2');if(!root)return;let box=root.querySelector('.cc2-inline-editor') as HTMLElement|null;if(!box){box=document.createElement('section');box.className='cc2-inline-editor cc2-panel';const main=root.querySelector('.cc2-main');main?.appendChild(box)}const storage=kind==='notes'?NOTE_KEY:JOURNAL_KEY;const title=kind==='notes'?'Notes':'Journal';box.innerHTML=`<div class="cc2-title">${title.toUpperCase()}</div><textarea data-cc-inline-editor rows="8" placeholder="${title} for ${activeName()}"></textarea><button type="button" data-cc-save-editor>Save ${title}</button>`;const ta=box.querySelector('textarea') as HTMLTextAreaElement;ta.value=localStorage.getItem(key(storage))||'';(box.querySelector('[data-cc-save-editor]') as HTMLButtonElement).onclick=()=>localStorage.setItem(key(storage),ta.value);box.scrollIntoView({behavior:'smooth',block:'center'})}
function wireLeft(){const root=document.getElementById('cc-character-dashboard-v2');if(!root)return;root.querySelectorAll<HTMLButtonElement>('.cc2-subnav button').forEach(b=>{if(b.dataset.ccWired==='1')return;b.dataset.ccWired='1';b.onclick=(e)=>{e.preventDefault();e.stopPropagation();const t=clean(b.textContent||'');root.querySelectorAll('.cc2-subnav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');if(/Character Sheet/i.test(t))root.querySelector('.cc2-hero')?.scrollIntoView({behavior:'smooth',block:'start'});else if(/Abilities/i.test(t))activatePrimary('Progression');else if(/Inventory/i.test(t))activatePrimary('Inventory');else if(/Conditions/i.test(t))root.querySelector('.cc2-cond')?.scrollIntoView({behavior:'smooth',block:'center'});else if(/Theme/i.test(t))(root.querySelector('.cc2-theme') as HTMLElement|null)?.focus();else if(/Journal/i.test(t))showEditor('journal');else if(/Notes/i.test(t))showEditor('notes')}})}
function fixPortraits(){const root=document.getElementById('cc-character-dashboard-v2');if(!root)return;root.querySelectorAll<HTMLImageElement>('.cc2-mini,.cc2-portrait').forEach(img=>{if(badPortrait(img.getAttribute('src')||'')){img.src=placeholder();img.alt='Character portrait placeholder'}})}
function installStyle(){if(document.getElementById(STYLE))return;const s=document.createElement('style');s.id=STYLE;s.textContent=`
[aria-label="Primary navigation"]{visibility:visible!important;opacity:1!important;position:relative!important;z-index:9999!important}
body[data-cc-primary-tab="gm-tools"] [aria-label="Primary navigation"]{display:flex!important}
#cc-mobile-resource-hud{display:none!important}
body[data-cc-primary-tab="dashboard"] #cc-mobile-resource-hud[data-visible="true"],body[data-cc-primary-tab="character"] #cc-mobile-resource-hud[data-visible="true"]{display:grid!important}
#cc-character-dashboard-v2 .cc2-track{display:grid!important;grid-template-columns:repeat(10,minmax(20px,1fr))!important;gap:6px!important}
#cc-character-dashboard-v2 .cc2-seg{cursor:pointer!important;min-height:28px!important}
#cc-character-dashboard-v2 .cc2-inline-editor{padding:14px;margin-top:12px}
#cc-character-dashboard-v2 .cc2-inline-editor textarea{width:100%;box-sizing:border-box;background:#0c121a;color:#f6ead0;border:1px solid var(--a);border-radius:8px;padding:10px}
#cc-character-dashboard-v2 .cc2-inline-editor button{margin-top:8px;padding:8px 12px;border:1px solid var(--a);border-radius:8px;background:#151a22;color:#fff}
`;document.head.appendChild(s)}
function forceHudScope(){const hud=document.getElementById('cc-mobile-resource-hud') as HTMLElement|null;if(!hud)return;const active=clean((primaryNav()?.querySelector('button.active,[aria-current="page"]') as HTMLElement|null)?.textContent||'').toLowerCase();hud.dataset.visible=String(active==='dashboard'||active==='character')}
function guardGM(e:Event){const b=(e.target as Element|null)?.closest('[aria-label="Primary navigation"] button') as HTMLButtonElement|null;if(!b||clean(b.textContent||'').toLowerCase()!=='gm tools')return;e.preventDefault();e.stopImmediatePropagation();const nav=primaryNav();nav?.querySelectorAll('button').forEach(x=>{x.classList.remove('active');x.removeAttribute('aria-current')});b.classList.add('active');b.setAttribute('aria-current','page');document.body.dataset.ccPrimaryTab='gm-tools';['cc-custom-spells','cc-runtime-gm-tools','cc-gm-rewards','cc-loot-boxes','cc-smart-loot'].forEach(id=>{const el=document.getElementById(id) as HTMLElement|null;if(el){el.hidden=false;el.style.display=''}});document.getElementById('cc-character-dashboard-v2')?.setAttribute('data-visible','false');forceHudScope()}
function apply(){installStyle();wireLeft();fixPortraits();paintHealth();paintMana();forceHudScope()}
document.addEventListener('click',guardGM,true);
document.addEventListener('click',e=>{if((e.target as Element)?.closest('[aria-label="Primary navigation"],.character-bar,.cc2-subnav'))setTimeout(apply,80)},true);
window.addEventListener('cc-resource-change',()=>setTimeout(()=>{paintHealth();paintMana();forceHudScope()},20));
window.addEventListener('cc:character-updated',()=>setTimeout(apply,60));
window.addEventListener('cc:campaign-changed',()=>setTimeout(apply,60));
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(apply,700),{once:true});else setTimeout(apply,700);
export { apply as applyFinalUiStabilityFix };
