const ID='cc-settings-panel';
const STYLE='cc-settings-panel-style';
const SOUND_KEY='cc-setting-sound';
const MOTION_KEY='cc-setting-motion';
function nav(){return document.querySelector('[aria-label="Primary navigation"]') as HTMLElement|null}
function label(btn:Element|null){return (btn?.textContent||'').replace(/✦/g,'').trim()}
function style(){if(document.getElementById(STYLE))return;const s=document.createElement('style');s.id=STYLE;s.textContent=`#${ID}{display:none;margin:14px 18px 24px;padding:16px;border:1px solid #b56b20;border-radius:14px;background:linear-gradient(180deg,#0b1018,#090d13);color:#f7ead1;box-shadow:0 8px 28px rgba(0,0,0,.32)}#${ID}[data-visible="true"]{display:block}#${ID} h2{margin:0 0 14px;color:#f3bf59;font-family:Georgia,serif}#${ID} .grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}#${ID} .card{padding:14px;border:1px solid #3b4654;border-radius:10px;background:#111821}#${ID} label{display:flex;align-items:center;justify-content:space-between;gap:12px;margin:10px 0}#${ID} select,#${ID} button{background:#0c131d;border:1px solid #b56b20;color:#fff;border-radius:8px;padding:9px 10px}#${ID} button{cursor:pointer;font-weight:700}#${ID} small{display:block;color:#aeb8c5;margin-top:6px}@media(max-width:760px){#${ID}{margin:8px}.grid{grid-template-columns:1fr!important}}`;document.head.appendChild(s)}
function ensureButton(){const n=nav();if(!n)return null;let b=n.querySelector('[data-cc-settings-tab]') as HTMLButtonElement|null;if(b)return b;b=document.createElement('button');b.type='button';b.dataset.ccSettingsTab='1';b.textContent='⚙ Settings';n.appendChild(b);return b}
function ensurePanel(){style();let p=document.getElementById(ID) as HTMLElement|null;if(p)return p;p=document.createElement('section');p.id=ID;p.dataset.visible='false';p.innerHTML=`<h2>⚙ Settings</h2><div class="grid"><div class="card"><b>Interface</b><label><span>Sound effects</span><input type="checkbox" data-sound></label><label><span>Animations</span><input type="checkbox" data-motion></label><small>These preferences are saved on this device.</small></div><div class="card"><b>Character appearance</b><label><span>Character theme</span><select data-theme><option>Dragon Gold</option><option>Arcane Purple</option><option>Frost Blue</option><option>Emerald Green</option><option>Shadow Grey</option><option>Sunset Orange</option></select></label><button type="button" data-portrait>Open Theme & Portrait</button></div><div class="card"><b>Help</b><button type="button" data-tutorial>Open Tutorial</button><small>Revisit the guided feature walkthrough at any time.</small></div><div class="card"><b>App</b><button type="button" data-reset>Reset local UI preferences</button><small>This does not delete campaign or cloud character data.</small></div></div>`;const main=document.querySelector('.app>main');if(main)main.insertAdjacentElement('afterend',p);else document.querySelector('.app')?.appendChild(p);return p}
function activeName(){return document.querySelector('#cc-character-dashboard-v2 .cc2-name')?.textContent?.trim()||document.querySelector('.character-bar select option:checked')?.textContent?.trim()||'Crawler'}
function themeKey(){return 'cc-sheet-theme:'+encodeURIComponent(activeName())}
function openPrimary(name:string){const n=nav();const b=[...n?.querySelectorAll('button')||[]].find(x=>label(x)===name) as HTMLButtonElement|undefined;b?.click()}
function wire(p:HTMLElement){if(p.dataset.wired==='1')return;p.dataset.wired='1';const sound=p.querySelector('[data-sound]') as HTMLInputElement;const motion=p.querySelector('[data-motion]') as HTMLInputElement;sound.checked=localStorage.getItem(SOUND_KEY)!=='off';motion.checked=localStorage.getItem(MOTION_KEY)!=='off';sound.onchange=()=>localStorage.setItem(SOUND_KEY,sound.checked?'on':'off');motion.onchange=()=>{localStorage.setItem(MOTION_KEY,motion.checked?'on':'off');document.documentElement.dataset.ccMotion=motion.checked?'on':'off'};const sel=p.querySelector('[data-theme]') as HTMLSelectElement;const stored=localStorage.getItem(themeKey())||'Ginger Fire';sel.value=stored==='Ginger Fire'?'Dragon Gold':stored;sel.onchange=()=>{localStorage.setItem(themeKey(),sel.value==='Dragon Gold'?'Ginger Fire':sel.value);window.dispatchEvent(new CustomEvent('cc:character-updated'))};(p.querySelector('[data-portrait]') as HTMLButtonElement).onclick=()=>{openPrimary('Character');setTimeout(()=>{const btn=[...document.querySelectorAll('#cc-character-dashboard-v2 .cc2-subnav button')].find(x=>/Theme & Portrait/i.test(x.textContent||'')) as HTMLButtonElement|undefined;btn?.click()},120)};(p.querySelector('[data-tutorial]') as HTMLButtonElement).onclick=()=>openPrimary('Tutorial');(p.querySelector('[data-reset]') as HTMLButtonElement).onclick=()=>{localStorage.removeItem(SOUND_KEY);localStorage.removeItem(MOTION_KEY);sound.checked=true;motion.checked=true}}
function show(on:boolean){const p=ensurePanel();p.dataset.visible=String(on);const main=document.querySelector('.app>main') as HTMLElement|null;if(main)main.style.display=on?'none':'';document.getElementById('cc-runtime-panel-host')?.setAttribute('style',on?'display:none':'')}
function install(){const b=ensureButton();const p=ensurePanel();wire(p);if(!b)return;b.onclick=e=>{e.preventDefault();e.stopPropagation();nav()?.querySelectorAll('button').forEach(x=>{x.classList.toggle('active',x===b);if(x===b)x.setAttribute('aria-current','page');else x.removeAttribute('aria-current')});show(true)};if(nav()?.dataset.ccSettingsDelegated!=='1'){nav()!.dataset.ccSettingsDelegated='1';nav()!.addEventListener('click',e=>{const t=(e.target as Element|null)?.closest('button');if(t&&t!==b&&label(t)!=='Settings')show(false)},true)}}
let tries=0;const timer=setInterval(()=>{tries++;install();if(nav()||tries>40)clearInterval(timer)},100);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
export { install as installSettingsPanel };
