import { cloudCampaignCharacters, cloudPushEvent } from './cloud';

const PANEL_ID='cc-smart-loot';
const ACTIVE_KEY='cc-active-campaign-id';
type Tier='Bronze'|'Silver'|'Gold'|'Epic'|'Legendary';
type Category='Weapon'|'Armor'|'Consumable'|'Scroll'|'Quest Item'|'Utility';
type SmartItem={name:string;detail:string;rarity:Tier;icon:string;type:'loot'|'scroll';category:Category;floor:number;custom:boolean};

const data:Record<Category,{icon:string,names:string[],details:string[]}>= {
 Weapon:{icon:'⚔️',names:['Ember-Edge Cleaver','Shockline Spear','Ricochet Handbow','Grinder Maul','Static Fang','Back-Alley Repeater'],details:['A hard-hitting weapon tuned for close fights.','Built to punish clustered enemies.','Reliable damage with an unusual secondary effect.']},
 Armor:{icon:'🛡️',names:['Reactive Crawler Vest','Impact-Weave Coat','Grav-Lock Boots','Mirrorplate Bracers','Hazard Hood','Kinetic Shoulder Guard'],details:['Protective gear reinforced for the current floor.','Trades comfort for survival when things get ugly.','Includes a situational defensive perk.']},
 Consumable:{icon:'🧪',names:['Emergency Health Ampoule','Mana Tonic','Adrenal Surge Dose','Smoke Bloom Capsule','Armor Foam Charge','Focus Chew'],details:['Single-use emergency support.','A consumable best saved for a bad round.','Temporary boost with a short duration.']},
 Scroll:{icon:'📜',names:['Scroll of Static Halo','Scroll of Crooked Ward','Scroll of Ember Hook','Scroll of Mirror Pulse','Scroll of Phantom Door','Scroll of Ashen Snare'],details:['CUSTOM scroll: casts once without Mana, then is consumed.','CUSTOM one-use magic generated for dungeon play.','CUSTOM scroll with a fixed effect and no permanent spell unlock.']},
 'Quest Item':{icon:'🔑',names:['Unmarked Objective Key','Faction Seal Fragment','Boss Access Token','Encrypted Floor Badge','Broken Quest Compass','Suspicious Contract Stub'],details:['A campaign hook the GM can tie to an objective.','May open a route, trigger an encounter, or advance a quest.','Important-looking enough that throwing it away seems unwise.']},
 Utility:{icon:'🧰',names:['Crawler Tool Roll','Phase Chalk','Rope Launcher','Noise Decoy','Trapwire Spool','Portable Barricade'],details:['Useful outside direct damage.','Supports exploration, traps, or improvised solutions.','A practical tool for solving dungeon problems creatively.']}
};
const categories=Object.keys(data) as Category[];
const pick=<T,>(a:T[])=>a[Math.floor(Math.random()*a.length)];
const clamp=(n:number,a:number,b:number)=>Math.max(a,Math.min(b,n));
function activeCampaign(){return localStorage.getItem(ACTIVE_KEY)||''}
function rarityRank(t:Tier){return ['Bronze','Silver','Gold','Epic','Legendary'].indexOf(t)}
function rollTier(base:Tier,floor:number):Tier{const tiers:Tier[]=['Bronze','Silver','Gold','Epic','Legendary'];const r=Math.random();let shift=r<.08?-1:r>.88?1:0;if(floor>=7&&r>.68)shift++;return tiers[clamp(rarityRank(base)+shift,0,4)]}
function uniqueCapacity(allowed:Category[]=categories){return (allowed.length?allowed:categories).reduce((sum,c)=>sum+data[c].names.length,0)}
function generateSmartLoot(count:number,baseTier:Tier,floor:number,allowed:Category[]=categories):SmartItem[]{
 const sourceCats=allowed.length?allowed:categories;
 const capacity=uniqueCapacity(sourceCats);
 const target=Math.min(Math.max(0,Math.floor(count)),capacity);
 const candidates=sourceCats.flatMap(category=>data[category].names.map(name=>({category,name}))).sort(()=>Math.random()-.5);
 return candidates.slice(0,target).map(({category,name})=>{const src=data[category];const rarity=rollTier(baseTier,floor);const scale=Math.max(1,floor);return {name,detail:`${pick(src.details)} Floor ${scale} scaling · ${rarity}.`,rarity,icon:src.icon,type:category==='Scroll'?'scroll':'loot',category,floor:scale,custom:category==='Scroll'} as SmartItem});
}
async function targets(select:HTMLSelectElement){select.innerHTML='';const id=activeCampaign();if(!id){select.innerHTML='<option value="">Choose active campaign</option>';return}try{const rows=await cloudCampaignCharacters(id) as any[];for(const r of rows){const o=document.createElement('option');o.value=r.id;o.textContent=r.name||r.data?.name||'Crawler';o.dataset.floor=String(r.data?.floor||r.floor||1);select.appendChild(o)}if(!rows.length)select.innerHTML='<option value="">No assigned crawlers</option>'}catch{select.innerHTML='<option value="">Could not load crawlers</option>'}}
function inject(){const host=document.getElementById('cc-loot-boxes');if(!host||document.getElementById(PANEL_ID))return;const w=document.createElement('div');w.id=PANEL_ID;w.style.cssText='margin-top:16px;padding-top:14px;border-top:1px solid rgba(230,171,82,.25)';w.innerHTML=`<h3>🧠 Smart Loot Builder</h3><p>Generate floor-scaled, rarity-weighted rewards or hand-pick categories before pushing.</p><div class="cc-lootbox-row"><select aria-label="Smart loot target"></select><select aria-label="Smart loot tier"><option>Bronze</option><option>Silver</option><option>Gold</option><option>Epic</option><option>Legendary</option></select><input aria-label="Smart loot count" type="number" min="1" max="30" inputmode="numeric" placeholder="Qty" value="3"></div><label>Floor <input aria-label="Smart loot floor" type="number" min="1" max="18" value="1" style="width:80px"></label><div data-cats style="display:flex;gap:8px;flex-wrap:wrap;margin:12px 0"></div><div class="cc-runtime-grid"><button data-smart-preview>🎲 Generate Preview</button><button data-smart-push>🔊 Push Generated Box</button></div><div class="cc-runtime-output" data-smart-out hidden></div><p data-smart-status aria-live="polite"></p>`;host.appendChild(w);const target=w.querySelector('[aria-label="Smart loot target"]') as HTMLSelectElement;const tier=w.querySelector('[aria-label="Smart loot tier"]') as HTMLSelectElement;const count=w.querySelector('[aria-label="Smart loot count"]') as HTMLInputElement;const floor=w.querySelector('[aria-label="Smart loot floor"]') as HTMLInputElement;const cats=w.querySelector('[data-cats]') as HTMLElement;const out=w.querySelector('[data-smart-out]') as HTMLElement;const status=w.querySelector('[data-smart-status]') as HTMLElement;categories.forEach(c=>{const l=document.createElement('label');l.innerHTML=`<input type="checkbox" value="${c}" checked> ${data[c].icon} ${c}`;cats.appendChild(l)});void targets(target);target.onchange=()=>{floor.value=target.selectedOptions[0]?.dataset.floor||floor.value};let current:SmartItem[]=[];
 const requestedCount=()=>{if(count.value.trim()==='')return null;const n=Number(count.value);if(!Number.isFinite(n))return null;return clamp(Math.floor(n),1,30)};
 count.addEventListener('focus',()=>count.select());
 count.addEventListener('input',()=>{current=[];status.textContent='';if(count.value==='')return;const n=Number(count.value);if(Number.isFinite(n)&&n>30)count.value='30';if(Number.isFinite(n)&&n<1&&count.value!=='0')count.value='1'});
 count.addEventListener('blur',()=>{if(count.value==='')count.value='3'});
 const build=()=>{const allowed=[...cats.querySelectorAll<HTMLInputElement>('input:checked')].map(x=>x.value as Category);if(!allowed.length){status.textContent='Choose at least one loot category.';current=[];out.hidden=true;return current}const requested=requestedCount();if(requested===null){status.textContent='Enter a loot quantity from 1 to 30.';current=[];out.hidden=true;return current}const capacity=uniqueCapacity(allowed);current=generateSmartLoot(requested,tier.value as Tier,clamp(Number(floor.value)||1,1,18),allowed);out.hidden=false;out.textContent=current.map((x,i)=>`${i+1}. ${x.icon} ${x.name} [${x.category} · ${x.rarity}]\n   ${x.detail}`).join('\n');status.textContent=requested>capacity?`Only ${capacity} unique items are available in the selected categories, so ${capacity} were generated with no duplicates.`:`✓ ${current.length} unique items generated.`;return current};
 (w.querySelector('[data-smart-preview]') as HTMLButtonElement).onclick=build;(w.querySelector('[data-smart-push]') as HTMLButtonElement).onclick=async()=>{const campaign=activeCampaign();if(!campaign||!target.value){status.textContent='Choose an active campaign and crawler.';return}const items=current.length?current:build();if(!items.length)return;try{await cloudPushEvent(campaign,'gm_loot_box',{boxTier:tier.value,title:`${tier.value} Smart Loot Box`,icon:tier.value==='Legendary'?'🌟':'🎁',items,pushedAt:new Date().toISOString(),source:'GM',smart:true,floor:Number(floor.value)||1},target.value);status.textContent=`✓ ${items.length} unique floor-scaled rewards pushed.`;current=[]}catch(e){status.textContent=`Could not push: ${e instanceof Error?e.message:String(e)}`}}}
function refresh(){inject();const t=document.querySelector(`#${PANEL_ID} [aria-label="Smart loot target"]`) as HTMLSelectElement|null;if(t)void targets(t)}
window.addEventListener('cc:campaign-changed',refresh);let pending=false;new MutationObserver(()=>{if(pending)return;pending=true;requestAnimationFrame(()=>{pending=false;refresh()})}).observe(document.documentElement,{subtree:true,childList:true});setTimeout(refresh,1200);
export { generateSmartLoot, uniqueCapacity };
