const TAB_LABEL='Tutorial';
const PANEL_ID='cc-tutorial-panel';
const STYLE_ID='cc-tutorial-style';
const hidden=new Map<HTMLElement,string>();

const steps=[
  ['🚀','Getting Started','Create or import a crawler, sign in for cloud backup, then choose or join a campaign.','Character'],
  ['🧑','Crawler Sheet','Edit stats, race, class, floor, level and crawler details. Your private crawlers stay private unless you assign one to a campaign.','Character'],
  ['❤️','Combat & Resources','Track Health, conditions, Mana and combat resources during play.','Combat'],
  ['✨','Spells','Use known spells, Mana, floor rewards, scrolls and spellbooks. Animal crawlers do not automatically start with Heal.','Progression'],
  ['🎒','Inventory & Loot','Manage equipment and inventory. GM-pushed loot can arrive with an animated reveal and be added to the targeted crawler.','Inventory'],
  ['🎲','Dice','Roll one or many polyhedral dice from the built-in dice tray.','Dice'],
  ['👥','Party','View the current campaign party and use side-by-side crawler sheets when running more than one crawler.','Party'],
  ['🏰','Campaigns','Create or join multiple campaigns. Each campaign has its own party, events and leaderboard.','Campaign'],
  ['🏆','Leaderboard','Leaderboards are campaign-only. Switching campaigns switches the leaderboard; there is no global crawler leaderboard.','Leaderboard'],
  ['📣','GM Tools','Campaign owners can generate encounters, loot and original spells, then push announcements and targeted rewards only inside their campaign.','GM Tools'],
  ['☁️','Cloud & Backup','Cloud saves are tied to your account. A campaign GM can only read crawler sheets explicitly assigned to that campaign.','Account'],
  ['📚','Rulebook Help','Use the rulebook assistant for game guidance while keeping official material separate from custom generated content.','Rulebook']
];

function addStyles(){if(document.getElementById(STYLE_ID))return;const s=document.createElement('style');s.id=STYLE_ID;s.textContent=`#${PANEL_ID}{padding:18px;max-width:1100px;margin:0 auto}.cc-tutorial-head{display:flex;gap:12px;align-items:center;justify-content:space-between;flex-wrap:wrap}.cc-tutorial-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:12px;margin-top:16px}.cc-tutorial-card{padding:15px;border:1px solid rgba(255,255,255,.12);border-radius:14px;background:rgba(255,255,255,.05)}.cc-tutorial-card h3{margin:0 0 8px}.cc-tutorial-card p{min-height:4.5em}.cc-tutorial-card button{font-weight:800}.cc-tutorial-note{padding:12px;border-radius:12px;background:rgba(101,71,216,.14);border:1px solid rgba(177,124,255,.3);margin-top:12px}`;document.head.appendChild(s)}
function restore(){for(const [el,display] of hidden){if(el.isConnected){el.style.display=display;el.removeAttribute('data-cc-tutorial-hidden')}}hidden.clear();document.getElementById(PANEL_ID)?.remove()}
function openNative(label:string){restore();const nav=document.querySelector('[aria-label="Primary navigation"]');const btn=[...(nav?.querySelectorAll('button')||[])].find(b=>b.textContent?.trim()===label) as HTMLButtonElement|undefined;btn?.click();btn?.scrollIntoView({behavior:'smooth',block:'nearest',inline:'center'})}
function showTutorial(tab:HTMLButtonElement){const main=document.querySelector('.app>main') as HTMLElement|null;if(!main)return;restore();const nav=document.querySelector('[aria-label="Primary navigation"]') as HTMLElement|null;for(const child of [...main.children] as HTMLElement[]){if(child===nav||child.contains(nav)||nav?.contains(child))continue;hidden.set(child,child.style.display);child.style.display='none';child.setAttribute('data-cc-tutorial-hidden','true')}const panel=document.createElement('section');panel.id=PANEL_ID;panel.innerHTML=`<div class="cc-tutorial-head"><div><h2>🎓 Crawler Companion Tutorial</h2><p>Learn the app one feature at a time. Use “Show me” to jump directly to that feature.</p></div><button data-cc-tutorial-start>Start with Character</button></div><div class="cc-tutorial-note"><strong>Campaign privacy:</strong> your account may own many crawlers and join many campaigns. A GM only sees crawler sheets assigned to that GM’s campaign, and each campaign has its own leaderboard and event history.</div><div class="cc-tutorial-grid">${steps.map(([icon,title,body,target])=>`<article class="cc-tutorial-card"><h3>${icon} ${title}</h3><p>${body}</p><button data-target="${target}">Show me →</button></article>`).join('')}</div>`;main.appendChild(panel);nav?.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b===tab));panel.querySelector<HTMLButtonElement>('[data-cc-tutorial-start]')!.onclick=()=>openNative('Character');panel.querySelectorAll<HTMLButtonElement>('[data-target]').forEach(b=>b.onclick=()=>openNative(b.dataset.target||'Dashboard'));window.scrollTo({top:0,behavior:'smooth'})}
function install(){addStyles();const nav=document.querySelector('[aria-label="Primary navigation"]');if(!nav||nav.querySelector('[data-cc-tutorial-tab]'))return;const tab=document.createElement('button');tab.type='button';tab.textContent=TAB_LABEL;tab.setAttribute('data-cc-tutorial-tab','true');tab.onclick=()=>showTutorial(tab);nav.appendChild(tab);nav.addEventListener('click',e=>{const target=e.target as HTMLElement;if(target.closest('button')!==tab&&document.getElementById(PANEL_ID))restore()},{capture:true})}
let queued=false;new MutationObserver(()=>{if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;install()})}).observe(document.documentElement,{subtree:true,childList:true});setTimeout(install,400);
